// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	admissionScoreFieldNames          = builder.RawFieldNames(&AdmissionScore{})
	admissionScoreRows                = strings.Join(admissionScoreFieldNames, ",")
	admissionScoreRowsExpectAutoSet   = strings.Join(stringx.Remove(admissionScoreFieldNames, "`id`", "`create_time`", "`created_at`"), ",")
	admissionScoreRowsWithPlaceHolder = strings.Join(stringx.Remove(admissionScoreFieldNames, "`id`", "`create_time`", "`created_at`"), "=?,") + "=?"
)

type (
	admissionScoreModel interface {
		Insert(ctx context.Context, data *AdmissionScore) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdmissionScore, error)
		Update(ctx context.Context, data *AdmissionScore) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdmissionScoreModel struct {
		sqlc.CachedConn
		table string
	}

	AdmissionScoreModel interface {
		admissionScoreModel
		FindByCondition(req *QueryScoreReq) ([]AdmissionScore, error)
		FindTrends(req *QueryScoreTrendReq) ([]ScoreTrend, error)
		FindMatchingColleges(req *GetMatchingCollegesReq) ([]MatchingCollege, error)
	}
)

func newAdmissionScoreModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAdmissionScoreModel {
	return &defaultAdmissionScoreModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`admission_score`",
	}
}

func (m *defaultAdmissionScoreModel) Insert(ctx context.Context, data *AdmissionScore) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, admissionScoreRowsExpectAutoSet)
	ret, err := m.ExecNoCacheCtx(ctx, query, data.Year, data.Province, data.CollegeName, data.MajorName, data.ScoreType, data.Batch, data.MinScore, data.MinRank, data.DataSource)

	return ret, err
}

func (m *defaultAdmissionScoreModel) FindOne(ctx context.Context, id int64) (*AdmissionScore, error) {
	admissionScoreIdKey := fmt.Sprintf("%s%v", cacheAdmissionScoreIdPrefix, id)
	var resp AdmissionScore
	err := m.QueryRowCtx(ctx, &resp, admissionScoreIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", admissionScoreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdmissionScoreModel) Update(ctx context.Context, data *AdmissionScore) error {
	admissionScoreIdKey := fmt.Sprintf("%s%v", cacheAdmissionScoreIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, admissionScoreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Year, data.Province, data.CollegeName, data.MajorName, data.ScoreType, data.Batch, data.MinScore, data.MinRank, data.DataSource, data.Id)
	}, admissionScoreIdKey)
	return err
}

func (m *defaultAdmissionScoreModel) Delete(ctx context.Context, id int64) error {
	admissionScoreIdKey := fmt.Sprintf("%s%v", cacheAdmissionScoreIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, admissionScoreIdKey)
	return err
}

func (m *defaultAdmissionScoreModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAdmissionScoreIdPrefix, primary)
}

func (m *defaultAdmissionScoreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", admissionScoreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}
