// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: score.proto

package scoreClient

import (
	"context"

	"lighthouse-volunteer/pb/lighthouse-volunteer/app/score/rpc/score"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdmissionScore           = score.AdmissionScore
	BatchGetCollegeInfoReq   = score.BatchGetCollegeInfoReq
	BatchGetCollegeInfoResp  = score.BatchGetCollegeInfoResp
	BatchGetMajorInfoReq     = score.BatchGetMajorInfoReq
	BatchGetMajorInfoResp    = score.BatchGetMajorInfoResp
	CollegeInfo              = score.CollegeInfo
	GetCollegeInfoReq        = score.GetCollegeInfoReq
	GetCollegeInfoResp       = score.GetCollegeInfoResp
	GetMajorInfoReq          = score.GetMajorInfoReq
	GetMajorInfoResp         = score.GetMajorInfoResp
	GetRankToScoreReq        = score.GetRankToScoreReq
	GetRankToScoreResp       = score.GetRankToScoreResp
	GetScoreTrendReq         = score.GetScoreTrendReq
	GetScoreTrendResp        = score.GetScoreTrendResp
	MajorInfo                = score.MajorInfo
	QueryAdmissionScoresReq  = score.QueryAdmissionScoresReq
	QueryAdmissionScoresResp = score.QueryAdmissionScoresResp
	ScoreTrendPoint          = score.ScoreTrendPoint

	Score interface {
		// 查询录取分数线
		QueryAdmissionScores(ctx context.Context, in *QueryAdmissionScoresReq, opts ...grpc.CallOption) (*QueryAdmissionScoresResp, error)
		// 获取学校信息
		GetCollegeInfo(ctx context.Context, in *GetCollegeInfoReq, opts ...grpc.CallOption) (*GetCollegeInfoResp, error)
		// 批量获取学校信息
		BatchGetCollegeInfo(ctx context.Context, in *BatchGetCollegeInfoReq, opts ...grpc.CallOption) (*BatchGetCollegeInfoResp, error)
		// 获取专业信息
		GetMajorInfo(ctx context.Context, in *GetMajorInfoReq, opts ...grpc.CallOption) (*GetMajorInfoResp, error)
		// 批量获取专业信息
		BatchGetMajorInfo(ctx context.Context, in *BatchGetMajorInfoReq, opts ...grpc.CallOption) (*BatchGetMajorInfoResp, error)
		// 获取分数线趋势
		GetScoreTrend(ctx context.Context, in *GetScoreTrendReq, opts ...grpc.CallOption) (*GetScoreTrendResp, error)
		// 获取位次对应的分数
		GetRankToScore(ctx context.Context, in *GetRankToScoreReq, opts ...grpc.CallOption) (*GetRankToScoreResp, error)
	}

	defaultScore struct {
		cli zrpc.Client
	}
)

func NewScore(cli zrpc.Client) Score {
	return &defaultScore{
		cli: cli,
	}
}

// 查询录取分数线
func (m *defaultScore) QueryAdmissionScores(ctx context.Context, in *QueryAdmissionScoresReq, opts ...grpc.CallOption) (*QueryAdmissionScoresResp, error) {
	client := score.NewScoreClient(m.cli.Conn())
	return client.QueryAdmissionScores(ctx, in, opts...)
}

// 获取学校信息
func (m *defaultScore) GetCollegeInfo(ctx context.Context, in *GetCollegeInfoReq, opts ...grpc.CallOption) (*GetCollegeInfoResp, error) {
	client := score.NewScoreClient(m.cli.Conn())
	return client.GetCollegeInfo(ctx, in, opts...)
}

// 批量获取学校信息
func (m *defaultScore) BatchGetCollegeInfo(ctx context.Context, in *BatchGetCollegeInfoReq, opts ...grpc.CallOption) (*BatchGetCollegeInfoResp, error) {
	client := score.NewScoreClient(m.cli.Conn())
	return client.BatchGetCollegeInfo(ctx, in, opts...)
}

// 获取专业信息
func (m *defaultScore) GetMajorInfo(ctx context.Context, in *GetMajorInfoReq, opts ...grpc.CallOption) (*GetMajorInfoResp, error) {
	client := score.NewScoreClient(m.cli.Conn())
	return client.GetMajorInfo(ctx, in, opts...)
}

// 批量获取专业信息
func (m *defaultScore) BatchGetMajorInfo(ctx context.Context, in *BatchGetMajorInfoReq, opts ...grpc.CallOption) (*BatchGetMajorInfoResp, error) {
	client := score.NewScoreClient(m.cli.Conn())
	return client.BatchGetMajorInfo(ctx, in, opts...)
}

// 获取分数线趋势
func (m *defaultScore) GetScoreTrend(ctx context.Context, in *GetScoreTrendReq, opts ...grpc.CallOption) (*GetScoreTrendResp, error) {
	client := score.NewScoreClient(m.cli.Conn())
	return client.GetScoreTrend(ctx, in, opts...)
}

// 获取位次对应的分数
func (m *defaultScore) GetRankToScore(ctx context.Context, in *GetRankToScoreReq, opts ...grpc.CallOption) (*GetRankToScoreResp, error) {
	client := score.NewScoreClient(m.cli.Conn())
	return client.GetRankToScore(ctx, in, opts...)
}
