// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: ai.proto

package server

import (
	"context"

	"lighthouse-volunteer/internal/logic"
	"lighthouse-volunteer/internal/svc"
	"lighthouse-volunteer/pb/lighthouse-volunteer/app/ai/rpc/ai"
)

type AiServer struct {
	svcCtx *svc.ServiceContext
	ai.UnimplementedAiServer
}

func NewAiServer(svcCtx *svc.ServiceContext) *AiServer {
	return &AiServer{
		svcCtx: svcCtx,
	}
}

// 生成志愿推荐
func (s *AiServer) GenerateVolunteerSuggestion(ctx context.Context, in *ai.GenerateVolunteerSuggestionReq) (*ai.GenerateVolunteerSuggestionResp, error) {
	l := logic.NewGenerateVolunteerSuggestionLogic(ctx, s.svcCtx)
	return l.GenerateVolunteerSuggestion(in)
}

// AI志愿咨询
func (s *AiServer) GetVolunteerAdvice(ctx context.Context, in *ai.GetVolunteerAdviceReq) (*ai.GetVolunteerAdviceResp, error) {
	l := logic.NewGetVolunteerAdviceLogic(ctx, s.svcCtx)
	return l.GetVolunteerAdvice(in)
}

// 分析用户画像
func (s *AiServer) AnalyzeUserProfile(ctx context.Context, in *ai.AnalyzeUserProfileReq) (*ai.AnalyzeUserProfileResp, error) {
	l := logic.NewAnalyzeUserProfileLogic(ctx, s.svcCtx)
	return l.AnalyzeUserProfile(in)
}

// 职业兴趣分析
func (s *AiServer) AnalyzeCareerInterest(ctx context.Context, in *ai.AnalyzeCareerInterestReq) (*ai.AnalyzeCareerInterestResp, error) {
	l := logic.NewAnalyzeCareerInterestLogic(ctx, s.svcCtx)
	return l.AnalyzeCareerInterest(in)
}

// 专业匹配度分析
func (s *AiServer) AnalyzeMajorMatching(ctx context.Context, in *ai.AnalyzeMajorMatchingReq) (*ai.AnalyzeMajorMatchingResp, error) {
	l := logic.NewAnalyzeMajorMatchingLogic(ctx, s.svcCtx)
	return l.AnalyzeMajorMatching(in)
}
