// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: score.proto

package server

import (
	"context"

	"lighthouse-volunteer/internal/logic"
	"lighthouse-volunteer/internal/svc"
	"lighthouse-volunteer/pb/lighthouse-volunteer/app/score/rpc/score"
)

type ScoreServer struct {
	svcCtx *svc.ServiceContext
	score.UnimplementedScoreServer
}

func NewScoreServer(svcCtx *svc.ServiceContext) *ScoreServer {
	return &ScoreServer{
		svcCtx: svcCtx,
	}
}

// 查询录取分数线
func (s *ScoreServer) QueryAdmissionScores(ctx context.Context, in *score.QueryAdmissionScoresReq) (*score.QueryAdmissionScoresResp, error) {
	l := logic.NewQueryAdmissionScoresLogic(ctx, s.svcCtx)
	return l.QueryAdmissionScores(in)
}

// 获取学校信息
func (s *ScoreServer) GetCollegeInfo(ctx context.Context, in *score.GetCollegeInfoReq) (*score.GetCollegeInfoResp, error) {
	l := logic.NewGetCollegeInfoLogic(ctx, s.svcCtx)
	return l.GetCollegeInfo(in)
}

// 批量获取学校信息
func (s *ScoreServer) BatchGetCollegeInfo(ctx context.Context, in *score.BatchGetCollegeInfoReq) (*score.BatchGetCollegeInfoResp, error) {
	l := logic.NewBatchGetCollegeInfoLogic(ctx, s.svcCtx)
	return l.BatchGetCollegeInfo(in)
}

// 获取专业信息
func (s *ScoreServer) GetMajorInfo(ctx context.Context, in *score.GetMajorInfoReq) (*score.GetMajorInfoResp, error) {
	l := logic.NewGetMajorInfoLogic(ctx, s.svcCtx)
	return l.GetMajorInfo(in)
}

// 批量获取专业信息
func (s *ScoreServer) BatchGetMajorInfo(ctx context.Context, in *score.BatchGetMajorInfoReq) (*score.BatchGetMajorInfoResp, error) {
	l := logic.NewBatchGetMajorInfoLogic(ctx, s.svcCtx)
	return l.BatchGetMajorInfo(in)
}

// 获取分数线趋势
func (s *ScoreServer) GetScoreTrend(ctx context.Context, in *score.GetScoreTrendReq) (*score.GetScoreTrendResp, error) {
	l := logic.NewGetScoreTrendLogic(ctx, s.svcCtx)
	return l.GetScoreTrend(in)
}

// 获取位次对应的分数
func (s *ScoreServer) GetRankToScore(ctx context.Context, in *score.GetRankToScoreReq) (*score.GetRankToScoreResp, error) {
	l := logic.NewGetRankToScoreLogic(ctx, s.svcCtx)
	return l.GetRankToScore(in)
}
