// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: spider.proto

package server

import (
	"context"

	"lighthouse-volunteer/internal/logic"
	"lighthouse-volunteer/internal/svc"
	"lighthouse-volunteer/pb/lighthouse-volunteer/app/spider/rpc/spider"
)

type SpiderServer struct {
	svcCtx *svc.ServiceContext
	spider.UnimplementedSpiderServer
}

func NewSpiderServer(svcCtx *svc.ServiceContext) *SpiderServer {
	return &SpiderServer{
		svcCtx: svcCtx,
	}
}

// 获取爬虫目标列表
func (s *SpiderServer) GetSpiderTargets(ctx context.Context, in *spider.GetSpiderTargetsReq) (*spider.GetSpiderTargetsResp, error) {
	l := logic.NewGetSpiderTargetsLogic(ctx, s.svcCtx)
	return l.GetSpiderTargets(in)
}

// 创建爬虫任务
func (s *SpiderServer) CreateSpiderTask(ctx context.Context, in *spider.CreateSpiderTaskReq) (*spider.CreateSpiderTaskResp, error) {
	l := logic.NewCreateSpiderTaskLogic(ctx, s.svcCtx)
	return l.CreateSpiderTask(in)
}

// 获取任务状态
func (s *SpiderServer) GetTaskStatus(ctx context.Context, in *spider.GetTaskStatusReq) (*spider.GetTaskStatusResp, error) {
	l := logic.NewGetTaskStatusLogic(ctx, s.svcCtx)
	return l.GetTaskStatus(in)
}

// 取消爬虫任务
func (s *SpiderServer) CancelSpiderTask(ctx context.Context, in *spider.CancelSpiderTaskReq) (*spider.CancelSpiderTaskResp, error) {
	l := logic.NewCancelSpiderTaskLogic(ctx, s.svcCtx)
	return l.CancelSpiderTask(in)
}

// 获取爬取结果
func (s *SpiderServer) GetSpiderResults(ctx context.Context, in *spider.GetSpiderResultsReq) (*spider.GetSpiderResultsResp, error) {
	l := logic.NewGetSpiderResultsLogic(ctx, s.svcCtx)
	return l.GetSpiderResults(in)
}
