// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: user.proto

package server

import (
	"context"

	"lighthouse-volunteer/internal/logic"
	"lighthouse-volunteer/internal/svc"
	"lighthouse-volunteer/pb/lighthouse-volunteer/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 用户登录/注册
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 获取用户信息
func (s *UserServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoReq) (*user.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// 更新用户档案
func (s *UserServer) UpdateUserProfile(ctx context.Context, in *user.UpdateUserProfileReq) (*user.UpdateUserProfileResp, error) {
	l := logic.NewUpdateUserProfileLogic(ctx, s.svcCtx)
	return l.UpdateUserProfile(in)
}

// 获取学长分享列表
func (s *UserServer) GetSeniorShares(ctx context.Context, in *user.GetSeniorSharesReq) (*user.GetSeniorSharesResp, error) {
	l := logic.NewGetSeniorSharesLogic(ctx, s.svcCtx)
	return l.GetSeniorShares(in)
}

// 创建学长分享
func (s *UserServer) CreateSeniorShare(ctx context.Context, in *user.CreateSeniorShareReq) (*user.CreateSeniorShareResp, error) {
	l := logic.NewCreateSeniorShareLogic(ctx, s.svcCtx)
	return l.CreateSeniorShare(in)
}

// 点赞/取消点赞分享
func (s *UserServer) LikeSeniorShare(ctx context.Context, in *user.LikeSeniorShareReq) (*user.LikeSeniorShareResp, error) {
	l := logic.NewLikeSeniorShareLogic(ctx, s.svcCtx)
	return l.LikeSeniorShare(in)
}

// 职业测评
func (s *UserServer) CareerAssessment(ctx context.Context, in *user.CareerAssessmentReq) (*user.CareerAssessmentResp, error) {
	l := logic.NewCareerAssessmentLogic(ctx, s.svcCtx)
	return l.CareerAssessment(in)
}

// 获取选科规划
func (s *UserServer) GetSubjectPlan(ctx context.Context, in *user.GetSubjectPlanReq) (*user.GetSubjectPlanResp, error) {
	l := logic.NewGetSubjectPlanLogic(ctx, s.svcCtx)
	return l.GetSubjectPlan(in)
}
