// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: ai.proto

package aiClient

import (
	"context"

	"lighthouse-volunteer/pb/lighthouse-volunteer/app/ai/rpc/ai"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeCareerInterestReq        = ai.AnalyzeCareerInterestReq
	AnalyzeCareerInterestResp       = ai.AnalyzeCareerInterestResp
	AnalyzeMajorMatchingReq         = ai.AnalyzeMajorMatchingReq
	AnalyzeMajorMatchingResp        = ai.AnalyzeMajorMatchingResp
	AnalyzeUserProfileReq           = ai.AnalyzeUserProfileReq
	AnalyzeUserProfileResp          = ai.AnalyzeUserProfileResp
	CollegeSuggestion               = ai.CollegeSuggestion
	GenerateVolunteerSuggestionReq  = ai.GenerateVolunteerSuggestionReq
	GenerateVolunteerSuggestionResp = ai.GenerateVolunteerSuggestionResp
	GetVolunteerAdviceReq           = ai.GetVolunteerAdviceReq
	GetVolunteerAdviceResp          = ai.GetVolunteerAdviceResp
	RelatedQuestion                 = ai.RelatedQuestion
	SuggestionCategory              = ai.SuggestionCategory

	Ai interface {
		// 生成志愿推荐
		GenerateVolunteerSuggestion(ctx context.Context, in *GenerateVolunteerSuggestionReq, opts ...grpc.CallOption) (*GenerateVolunteerSuggestionResp, error)
		// AI志愿咨询
		GetVolunteerAdvice(ctx context.Context, in *GetVolunteerAdviceReq, opts ...grpc.CallOption) (*GetVolunteerAdviceResp, error)
		// 分析用户画像
		AnalyzeUserProfile(ctx context.Context, in *AnalyzeUserProfileReq, opts ...grpc.CallOption) (*AnalyzeUserProfileResp, error)
		// 职业兴趣分析
		AnalyzeCareerInterest(ctx context.Context, in *AnalyzeCareerInterestReq, opts ...grpc.CallOption) (*AnalyzeCareerInterestResp, error)
		// 专业匹配度分析
		AnalyzeMajorMatching(ctx context.Context, in *AnalyzeMajorMatchingReq, opts ...grpc.CallOption) (*AnalyzeMajorMatchingResp, error)
	}

	defaultAi struct {
		cli zrpc.Client
	}
)

func NewAi(cli zrpc.Client) Ai {
	return &defaultAi{
		cli: cli,
	}
}

// 生成志愿推荐
func (m *defaultAi) GenerateVolunteerSuggestion(ctx context.Context, in *GenerateVolunteerSuggestionReq, opts ...grpc.CallOption) (*GenerateVolunteerSuggestionResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.GenerateVolunteerSuggestion(ctx, in, opts...)
}

// AI志愿咨询
func (m *defaultAi) GetVolunteerAdvice(ctx context.Context, in *GetVolunteerAdviceReq, opts ...grpc.CallOption) (*GetVolunteerAdviceResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.GetVolunteerAdvice(ctx, in, opts...)
}

// 分析用户画像
func (m *defaultAi) AnalyzeUserProfile(ctx context.Context, in *AnalyzeUserProfileReq, opts ...grpc.CallOption) (*AnalyzeUserProfileResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.AnalyzeUserProfile(ctx, in, opts...)
}

// 职业兴趣分析
func (m *defaultAi) AnalyzeCareerInterest(ctx context.Context, in *AnalyzeCareerInterestReq, opts ...grpc.CallOption) (*AnalyzeCareerInterestResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.AnalyzeCareerInterest(ctx, in, opts...)
}

// 专业匹配度分析
func (m *defaultAi) AnalyzeMajorMatching(ctx context.Context, in *AnalyzeMajorMatchingReq, opts ...grpc.CallOption) (*AnalyzeMajorMatchingResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.AnalyzeMajorMatching(ctx, in, opts...)
}
