// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: app/user/rpc/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求和响应消息
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                        // 微信授权码
	EncryptedData string                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // 加密数据
	Iv            string                 `protobuf:"bytes,3,opt,name=iv,proto3" json:"iv,omitempty"`                                            // 初始向量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginReq) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

func (x *LoginReq) GetIv() string {
	if x != nil {
		return x.Iv
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OpenId        string                 `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	UnionId       string                 `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
	SessionKey    string                 `protobuf:"bytes,4,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	NeedProfile   bool                   `protobuf:"varint,5,opt,name=need_profile,json=needProfile,proto3" json:"need_profile,omitempty"` // 是否需要完善档案
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResp) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LoginResp) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *LoginResp) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *LoginResp) GetNeedProfile() bool {
	if x != nil {
		return x.NeedProfile
	}
	return false
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OpenId        string                 `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	UnionId       string                 `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Province      string                 `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime string                 `protobuf:"bytes,10,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_app_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserInfo) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *UserInfo) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UserProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GraduationYear  int32                  `protobuf:"varint,3,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Province        string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType       int32                  `protobuf:"varint,5,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	Subjects        string                 `protobuf:"bytes,6,opt,name=subjects,proto3" json:"subjects,omitempty"`
	TotalScore      int32                  `protobuf:"varint,7,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Rank            int32                  `protobuf:"varint,8,opt,name=rank,proto3" json:"rank,omitempty"`
	TargetCollege   string                 `protobuf:"bytes,9,opt,name=target_college,json=targetCollege,proto3" json:"target_college,omitempty"`
	TargetMajor     string                 `protobuf:"bytes,10,opt,name=target_major,json=targetMajor,proto3" json:"target_major,omitempty"`
	InterestTags    string                 `protobuf:"bytes,11,opt,name=interest_tags,json=interestTags,proto3" json:"interest_tags,omitempty"`
	PersonalityType string                 `protobuf:"bytes,12,opt,name=personality_type,json=personalityType,proto3" json:"personality_type,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_app_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetGraduationYear() int32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

func (x *UserProfile) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserProfile) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *UserProfile) GetSubjects() string {
	if x != nil {
		return x.Subjects
	}
	return ""
}

func (x *UserProfile) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *UserProfile) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *UserProfile) GetTargetCollege() string {
	if x != nil {
		return x.TargetCollege
	}
	return ""
}

func (x *UserProfile) GetTargetMajor() string {
	if x != nil {
		return x.TargetMajor
	}
	return ""
}

func (x *UserProfile) GetInterestTags() string {
	if x != nil {
		return x.InterestTags
	}
	return ""
}

func (x *UserProfile) GetPersonalityType() string {
	if x != nil {
		return x.PersonalityType
	}
	return ""
}

func (x *UserProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateUserProfileReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GraduationYear  int32                  `protobuf:"varint,2,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Province        string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType       int32                  `protobuf:"varint,4,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	Subjects        string                 `protobuf:"bytes,5,opt,name=subjects,proto3" json:"subjects,omitempty"`
	TotalScore      int32                  `protobuf:"varint,6,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Rank            int32                  `protobuf:"varint,7,opt,name=rank,proto3" json:"rank,omitempty"`
	TargetCollege   string                 `protobuf:"bytes,8,opt,name=target_college,json=targetCollege,proto3" json:"target_college,omitempty"`
	TargetMajor     string                 `protobuf:"bytes,9,opt,name=target_major,json=targetMajor,proto3" json:"target_major,omitempty"`
	InterestTags    string                 `protobuf:"bytes,10,opt,name=interest_tags,json=interestTags,proto3" json:"interest_tags,omitempty"`
	PersonalityType string                 `protobuf:"bytes,11,opt,name=personality_type,json=personalityType,proto3" json:"personality_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserProfileReq) Reset() {
	*x = UpdateUserProfileReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileReq) ProtoMessage() {}

func (x *UpdateUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserProfileReq) GetGraduationYear() int32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

func (x *UpdateUserProfileReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UpdateUserProfileReq) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *UpdateUserProfileReq) GetSubjects() string {
	if x != nil {
		return x.Subjects
	}
	return ""
}

func (x *UpdateUserProfileReq) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *UpdateUserProfileReq) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *UpdateUserProfileReq) GetTargetCollege() string {
	if x != nil {
		return x.TargetCollege
	}
	return ""
}

func (x *UpdateUserProfileReq) GetTargetMajor() string {
	if x != nil {
		return x.TargetMajor
	}
	return ""
}

func (x *UpdateUserProfileReq) GetInterestTags() string {
	if x != nil {
		return x.InterestTags
	}
	return ""
}

func (x *UpdateUserProfileReq) GetPersonalityType() string {
	if x != nil {
		return x.PersonalityType
	}
	return ""
}

type UpdateUserProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResp) Reset() {
	*x = UpdateUserProfileResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResp) ProtoMessage() {}

func (x *UpdateUserProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserProfileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSeniorSharesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ShareType     string                 `protobuf:"bytes,3,opt,name=share_type,json=shareType,proto3" json:"share_type,omitempty"`
	CollegeCode   string                 `protobuf:"bytes,4,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	MajorCode     string                 `protobuf:"bytes,5,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"`
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`  // time, hot
	UserId        int64                  `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用于检查是否点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeniorSharesReq) Reset() {
	*x = GetSeniorSharesReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeniorSharesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeniorSharesReq) ProtoMessage() {}

func (x *GetSeniorSharesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeniorSharesReq.ProtoReflect.Descriptor instead.
func (*GetSeniorSharesReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetSeniorSharesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSeniorSharesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetSeniorSharesReq) GetShareType() string {
	if x != nil {
		return x.ShareType
	}
	return ""
}

func (x *GetSeniorSharesReq) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

func (x *GetSeniorSharesReq) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *GetSeniorSharesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetSeniorSharesReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetSeniorSharesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSeniorSharesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shares        []*SeniorShare         `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeniorSharesResp) Reset() {
	*x = GetSeniorSharesResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeniorSharesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeniorSharesResp) ProtoMessage() {}

func (x *GetSeniorSharesResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeniorSharesResp.ProtoReflect.Descriptor instead.
func (*GetSeniorSharesResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetSeniorSharesResp) GetShares() []*SeniorShare {
	if x != nil {
		return x.Shares
	}
	return nil
}

func (x *GetSeniorSharesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSeniorSharesResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSeniorSharesResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SeniorShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CollegeCode   string                 `protobuf:"bytes,3,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	CollegeName   string                 `protobuf:"bytes,4,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	MajorCode     string                 `protobuf:"bytes,5,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	MajorName     string                 `protobuf:"bytes,6,opt,name=major_name,json=majorName,proto3" json:"major_name,omitempty"`
	ShareType     string                 `protobuf:"bytes,7,opt,name=share_type,json=shareType,proto3" json:"share_type,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Tags          string                 `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	IsAnonymous   int32                  `protobuf:"varint,11,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	ViewCount     int32                  `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int32                  `protobuf:"varint,13,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int32                  `protobuf:"varint,14,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	Status        int32                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,16,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	User          *ShareUser             `protobuf:"bytes,17,opt,name=user,proto3" json:"user,omitempty"`
	IsLiked       bool                   `protobuf:"varint,18,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeniorShare) Reset() {
	*x = SeniorShare{}
	mi := &file_app_user_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeniorShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeniorShare) ProtoMessage() {}

func (x *SeniorShare) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeniorShare.ProtoReflect.Descriptor instead.
func (*SeniorShare) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *SeniorShare) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeniorShare) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeniorShare) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

func (x *SeniorShare) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *SeniorShare) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *SeniorShare) GetMajorName() string {
	if x != nil {
		return x.MajorName
	}
	return ""
}

func (x *SeniorShare) GetShareType() string {
	if x != nil {
		return x.ShareType
	}
	return ""
}

func (x *SeniorShare) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SeniorShare) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SeniorShare) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *SeniorShare) GetIsAnonymous() int32 {
	if x != nil {
		return x.IsAnonymous
	}
	return 0
}

func (x *SeniorShare) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *SeniorShare) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *SeniorShare) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *SeniorShare) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SeniorShare) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *SeniorShare) GetUser() *ShareUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SeniorShare) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *SeniorShare) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ShareUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareUser) Reset() {
	*x = ShareUser{}
	mi := &file_app_user_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareUser) ProtoMessage() {}

func (x *ShareUser) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareUser.ProtoReflect.Descriptor instead.
func (*ShareUser) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *ShareUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ShareUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateSeniorShareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CollegeCode   string                 `protobuf:"bytes,2,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	CollegeName   string                 `protobuf:"bytes,3,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	MajorCode     string                 `protobuf:"bytes,4,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	MajorName     string                 `protobuf:"bytes,5,opt,name=major_name,json=majorName,proto3" json:"major_name,omitempty"`
	ShareType     string                 `protobuf:"bytes,6,opt,name=share_type,json=shareType,proto3" json:"share_type,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Tags          string                 `protobuf:"bytes,9,opt,name=tags,proto3" json:"tags,omitempty"`
	IsAnonymous   int32                  `protobuf:"varint,10,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeniorShareReq) Reset() {
	*x = CreateSeniorShareReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeniorShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeniorShareReq) ProtoMessage() {}

func (x *CreateSeniorShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeniorShareReq.ProtoReflect.Descriptor instead.
func (*CreateSeniorShareReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSeniorShareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSeniorShareReq) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

func (x *CreateSeniorShareReq) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *CreateSeniorShareReq) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *CreateSeniorShareReq) GetMajorName() string {
	if x != nil {
		return x.MajorName
	}
	return ""
}

func (x *CreateSeniorShareReq) GetShareType() string {
	if x != nil {
		return x.ShareType
	}
	return ""
}

func (x *CreateSeniorShareReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSeniorShareReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateSeniorShareReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *CreateSeniorShareReq) GetIsAnonymous() int32 {
	if x != nil {
		return x.IsAnonymous
	}
	return 0
}

type CreateSeniorShareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       int64                  `protobuf:"varint,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeniorShareResp) Reset() {
	*x = CreateSeniorShareResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeniorShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeniorShareResp) ProtoMessage() {}

func (x *CreateSeniorShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeniorShareResp.ProtoReflect.Descriptor instead.
func (*CreateSeniorShareResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSeniorShareResp) GetShareId() int64 {
	if x != nil {
		return x.ShareId
	}
	return 0
}

type LikeSeniorShareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShareId       int64                  `protobuf:"varint,2,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	Like          bool                   `protobuf:"varint,3,opt,name=like,proto3" json:"like,omitempty"` // true-点赞，false-取消点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeSeniorShareReq) Reset() {
	*x = LikeSeniorShareReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeSeniorShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeSeniorShareReq) ProtoMessage() {}

func (x *LikeSeniorShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeSeniorShareReq.ProtoReflect.Descriptor instead.
func (*LikeSeniorShareReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{14}
}

func (x *LikeSeniorShareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeSeniorShareReq) GetShareId() int64 {
	if x != nil {
		return x.ShareId
	}
	return 0
}

func (x *LikeSeniorShareReq) GetLike() bool {
	if x != nil {
		return x.Like
	}
	return false
}

type LikeSeniorShareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LikeCount     int32                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeSeniorShareResp) Reset() {
	*x = LikeSeniorShareResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeSeniorShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeSeniorShareResp) ProtoMessage() {}

func (x *LikeSeniorShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeSeniorShareResp.ProtoReflect.Descriptor instead.
func (*LikeSeniorShareResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{15}
}

func (x *LikeSeniorShareResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LikeSeniorShareResp) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type CareerAssessmentReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssessmentType string                 `protobuf:"bytes,2,opt,name=assessment_type,json=assessmentType,proto3" json:"assessment_type,omitempty"`
	Answers        string                 `protobuf:"bytes,3,opt,name=answers,proto3" json:"answers,omitempty"` // JSON字符串
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CareerAssessmentReq) Reset() {
	*x = CareerAssessmentReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareerAssessmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareerAssessmentReq) ProtoMessage() {}

func (x *CareerAssessmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareerAssessmentReq.ProtoReflect.Descriptor instead.
func (*CareerAssessmentReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{16}
}

func (x *CareerAssessmentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CareerAssessmentReq) GetAssessmentType() string {
	if x != nil {
		return x.AssessmentType
	}
	return ""
}

func (x *CareerAssessmentReq) GetAnswers() string {
	if x != nil {
		return x.Answers
	}
	return ""
}

type CareerAssessmentResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssessmentType  string                 `protobuf:"bytes,1,opt,name=assessment_type,json=assessmentType,proto3" json:"assessment_type,omitempty"`
	Result          string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ScoreDetails    string                 `protobuf:"bytes,3,opt,name=score_details,json=scoreDetails,proto3" json:"score_details,omitempty"`
	Recommendations string                 `protobuf:"bytes,4,opt,name=recommendations,proto3" json:"recommendations,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CareerAssessmentResp) Reset() {
	*x = CareerAssessmentResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareerAssessmentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareerAssessmentResp) ProtoMessage() {}

func (x *CareerAssessmentResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareerAssessmentResp.ProtoReflect.Descriptor instead.
func (*CareerAssessmentResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{17}
}

func (x *CareerAssessmentResp) GetAssessmentType() string {
	if x != nil {
		return x.AssessmentType
	}
	return ""
}

func (x *CareerAssessmentResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CareerAssessmentResp) GetScoreDetails() string {
	if x != nil {
		return x.ScoreDetails
	}
	return ""
}

func (x *CareerAssessmentResp) GetRecommendations() string {
	if x != nil {
		return x.Recommendations
	}
	return ""
}

func (x *CareerAssessmentResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetSubjectPlanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      string                 `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType     int32                  `protobuf:"varint,2,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	Subjects      string                 `protobuf:"bytes,3,opt,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubjectPlanReq) Reset() {
	*x = GetSubjectPlanReq{}
	mi := &file_app_user_rpc_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubjectPlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubjectPlanReq) ProtoMessage() {}

func (x *GetSubjectPlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubjectPlanReq.ProtoReflect.Descriptor instead.
func (*GetSubjectPlanReq) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetSubjectPlanReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetSubjectPlanReq) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *GetSubjectPlanReq) GetSubjects() string {
	if x != nil {
		return x.Subjects
	}
	return ""
}

type GetSubjectPlanResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubjectCombination string                 `protobuf:"bytes,1,opt,name=subject_combination,json=subjectCombination,proto3" json:"subject_combination,omitempty"`
	RecommendedMajors  string                 `protobuf:"bytes,2,opt,name=recommended_majors,json=recommendedMajors,proto3" json:"recommended_majors,omitempty"`
	SuccessRate        float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgScoreRequired   int32                  `protobuf:"varint,4,opt,name=avg_score_required,json=avgScoreRequired,proto3" json:"avg_score_required,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSubjectPlanResp) Reset() {
	*x = GetSubjectPlanResp{}
	mi := &file_app_user_rpc_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubjectPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubjectPlanResp) ProtoMessage() {}

func (x *GetSubjectPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubjectPlanResp.ProtoReflect.Descriptor instead.
func (*GetSubjectPlanResp) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetSubjectPlanResp) GetSubjectCombination() string {
	if x != nil {
		return x.SubjectCombination
	}
	return ""
}

func (x *GetSubjectPlanResp) GetRecommendedMajors() string {
	if x != nil {
		return x.RecommendedMajors
	}
	return ""
}

func (x *GetSubjectPlanResp) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *GetSubjectPlanResp) GetAvgScoreRequired() int32 {
	if x != nil {
		return x.AvgScoreRequired
	}
	return 0
}

var File_app_user_rpc_user_proto protoreflect.FileDescriptor

const file_app_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x17app/user/rpc/user.proto\x12\x04user\"U\n" +
	"\bLoginReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\tR\rencryptedData\x12\x0e\n" +
	"\x02iv\x18\x03 \x01(\tR\x02iv\"\x9c\x01\n" +
	"\tLoginResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x19\n" +
	"\bunion_id\x18\x03 \x01(\tR\aunionId\x12\x1f\n" +
	"\vsession_key\x18\x04 \x01(\tR\n" +
	"sessionKey\x12!\n" +
	"\fneed_profile\x18\x05 \x01(\bR\vneedProfile\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"5\n" +
	"\x0fGetUserInfoResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"\xd6\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x19\n" +
	"\bunion_id\x18\x03 \x01(\tR\aunionId\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x1a\n" +
	"\bprovince\x18\a \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12&\n" +
	"\x0flast_login_time\x18\n" +
	" \x01(\tR\rlastLoginTime\x12+\n" +
	"\aprofile\x18\v \x01(\v2\x11.user.UserProfileR\aprofile\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\xc3\x03\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12'\n" +
	"\x0fgraduation_year\x18\x03 \x01(\x05R\x0egraduationYear\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x05 \x01(\x05R\tscoreType\x12\x1a\n" +
	"\bsubjects\x18\x06 \x01(\tR\bsubjects\x12\x1f\n" +
	"\vtotal_score\x18\a \x01(\x05R\n" +
	"totalScore\x12\x12\n" +
	"\x04rank\x18\b \x01(\x05R\x04rank\x12%\n" +
	"\x0etarget_college\x18\t \x01(\tR\rtargetCollege\x12!\n" +
	"\ftarget_major\x18\n" +
	" \x01(\tR\vtargetMajor\x12#\n" +
	"\rinterest_tags\x18\v \x01(\tR\finterestTags\x12)\n" +
	"\x10personality_type\x18\f \x01(\tR\x0fpersonalityType\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xfe\x02\n" +
	"\x14UpdateUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fgraduation_year\x18\x02 \x01(\x05R\x0egraduationYear\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x04 \x01(\x05R\tscoreType\x12\x1a\n" +
	"\bsubjects\x18\x05 \x01(\tR\bsubjects\x12\x1f\n" +
	"\vtotal_score\x18\x06 \x01(\x05R\n" +
	"totalScore\x12\x12\n" +
	"\x04rank\x18\a \x01(\x05R\x04rank\x12%\n" +
	"\x0etarget_college\x18\b \x01(\tR\rtargetCollege\x12!\n" +
	"\ftarget_major\x18\t \x01(\tR\vtargetMajor\x12#\n" +
	"\rinterest_tags\x18\n" +
	" \x01(\tR\finterestTags\x12)\n" +
	"\x10personality_type\x18\v \x01(\tR\x0fpersonalityType\"1\n" +
	"\x15UpdateUserProfileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf2\x01\n" +
	"\x12GetSeniorSharesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"share_type\x18\x03 \x01(\tR\tshareType\x12!\n" +
	"\fcollege_code\x18\x04 \x01(\tR\vcollegeCode\x12\x1d\n" +
	"\n" +
	"major_code\x18\x05 \x01(\tR\tmajorCode\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x17\n" +
	"\auser_id\x18\b \x01(\x03R\x06userId\"\x87\x01\n" +
	"\x13GetSeniorSharesResp\x12)\n" +
	"\x06shares\x18\x01 \x03(\v2\x11.user.SeniorShareR\x06shares\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xbd\x04\n" +
	"\vSeniorShare\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fcollege_code\x18\x03 \x01(\tR\vcollegeCode\x12!\n" +
	"\fcollege_name\x18\x04 \x01(\tR\vcollegeName\x12\x1d\n" +
	"\n" +
	"major_code\x18\x05 \x01(\tR\tmajorCode\x12\x1d\n" +
	"\n" +
	"major_name\x18\x06 \x01(\tR\tmajorName\x12\x1d\n" +
	"\n" +
	"share_type\x18\a \x01(\tR\tshareType\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\t \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x01(\tR\x04tags\x12!\n" +
	"\fis_anonymous\x18\v \x01(\x05R\visAnonymous\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\r \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x0e \x01(\x05R\fcommentCount\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\x12!\n" +
	"\fpublished_at\x18\x10 \x01(\tR\vpublishedAt\x12#\n" +
	"\x04user\x18\x11 \x01(\v2\x0f.user.ShareUserR\x04user\x12\x19\n" +
	"\bis_liked\x18\x12 \x01(\bR\aisLiked\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tR\tcreatedAt\"?\n" +
	"\tShareUser\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\"\xb9\x02\n" +
	"\x14CreateSeniorShareReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fcollege_code\x18\x02 \x01(\tR\vcollegeCode\x12!\n" +
	"\fcollege_name\x18\x03 \x01(\tR\vcollegeName\x12\x1d\n" +
	"\n" +
	"major_code\x18\x04 \x01(\tR\tmajorCode\x12\x1d\n" +
	"\n" +
	"major_name\x18\x05 \x01(\tR\tmajorName\x12\x1d\n" +
	"\n" +
	"share_type\x18\x06 \x01(\tR\tshareType\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\t \x01(\tR\x04tags\x12!\n" +
	"\fis_anonymous\x18\n" +
	" \x01(\x05R\visAnonymous\"2\n" +
	"\x15CreateSeniorShareResp\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\x03R\ashareId\"\\\n" +
	"\x12LikeSeniorShareReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bshare_id\x18\x02 \x01(\x03R\ashareId\x12\x12\n" +
	"\x04like\x18\x03 \x01(\bR\x04like\"N\n" +
	"\x13LikeSeniorShareResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x05R\tlikeCount\"q\n" +
	"\x13CareerAssessmentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fassessment_type\x18\x02 \x01(\tR\x0eassessmentType\x12\x18\n" +
	"\aanswers\x18\x03 \x01(\tR\aanswers\"\xc5\x01\n" +
	"\x14CareerAssessmentResp\x12'\n" +
	"\x0fassessment_type\x18\x01 \x01(\tR\x0eassessmentType\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12#\n" +
	"\rscore_details\x18\x03 \x01(\tR\fscoreDetails\x12(\n" +
	"\x0frecommendations\x18\x04 \x01(\tR\x0frecommendations\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"j\n" +
	"\x11GetSubjectPlanReq\x12\x1a\n" +
	"\bprovince\x18\x01 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x02 \x01(\x05R\tscoreType\x12\x1a\n" +
	"\bsubjects\x18\x03 \x01(\tR\bsubjects\"\xc5\x01\n" +
	"\x12GetSubjectPlanResp\x12/\n" +
	"\x13subject_combination\x18\x01 \x01(\tR\x12subjectCombination\x12-\n" +
	"\x12recommended_majors\x18\x02 \x01(\tR\x11recommendedMajors\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x12,\n" +
	"\x12avg_score_required\x18\x04 \x01(\x05R\x10avgScoreRequired2\xa8\x04\n" +
	"\x04User\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x12:\n" +
	"\vGetUserInfo\x12\x14.user.GetUserInfoReq\x1a\x15.user.GetUserInfoResp\x12L\n" +
	"\x11UpdateUserProfile\x12\x1a.user.UpdateUserProfileReq\x1a\x1b.user.UpdateUserProfileResp\x12F\n" +
	"\x0fGetSeniorShares\x12\x18.user.GetSeniorSharesReq\x1a\x19.user.GetSeniorSharesResp\x12L\n" +
	"\x11CreateSeniorShare\x12\x1a.user.CreateSeniorShareReq\x1a\x1b.user.CreateSeniorShareResp\x12F\n" +
	"\x0fLikeSeniorShare\x12\x18.user.LikeSeniorShareReq\x1a\x19.user.LikeSeniorShareResp\x12I\n" +
	"\x10CareerAssessment\x12\x19.user.CareerAssessmentReq\x1a\x1a.user.CareerAssessmentResp\x12C\n" +
	"\x0eGetSubjectPlan\x12\x17.user.GetSubjectPlanReq\x1a\x18.user.GetSubjectPlanRespB(Z&lighthouse-volunteer/app/user/rpc/userb\x06proto3"

var (
	file_app_user_rpc_user_proto_rawDescOnce sync.Once
	file_app_user_rpc_user_proto_rawDescData []byte
)

func file_app_user_rpc_user_proto_rawDescGZIP() []byte {
	file_app_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_app_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_user_rpc_user_proto_rawDesc), len(file_app_user_rpc_user_proto_rawDesc)))
	})
	return file_app_user_rpc_user_proto_rawDescData
}

var file_app_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_app_user_rpc_user_proto_goTypes = []any{
	(*LoginReq)(nil),              // 0: user.LoginReq
	(*LoginResp)(nil),             // 1: user.LoginResp
	(*GetUserInfoReq)(nil),        // 2: user.GetUserInfoReq
	(*GetUserInfoResp)(nil),       // 3: user.GetUserInfoResp
	(*UserInfo)(nil),              // 4: user.UserInfo
	(*UserProfile)(nil),           // 5: user.UserProfile
	(*UpdateUserProfileReq)(nil),  // 6: user.UpdateUserProfileReq
	(*UpdateUserProfileResp)(nil), // 7: user.UpdateUserProfileResp
	(*GetSeniorSharesReq)(nil),    // 8: user.GetSeniorSharesReq
	(*GetSeniorSharesResp)(nil),   // 9: user.GetSeniorSharesResp
	(*SeniorShare)(nil),           // 10: user.SeniorShare
	(*ShareUser)(nil),             // 11: user.ShareUser
	(*CreateSeniorShareReq)(nil),  // 12: user.CreateSeniorShareReq
	(*CreateSeniorShareResp)(nil), // 13: user.CreateSeniorShareResp
	(*LikeSeniorShareReq)(nil),    // 14: user.LikeSeniorShareReq
	(*LikeSeniorShareResp)(nil),   // 15: user.LikeSeniorShareResp
	(*CareerAssessmentReq)(nil),   // 16: user.CareerAssessmentReq
	(*CareerAssessmentResp)(nil),  // 17: user.CareerAssessmentResp
	(*GetSubjectPlanReq)(nil),     // 18: user.GetSubjectPlanReq
	(*GetSubjectPlanResp)(nil),    // 19: user.GetSubjectPlanResp
}
var file_app_user_rpc_user_proto_depIdxs = []int32{
	4,  // 0: user.GetUserInfoResp.user:type_name -> user.UserInfo
	5,  // 1: user.UserInfo.profile:type_name -> user.UserProfile
	10, // 2: user.GetSeniorSharesResp.shares:type_name -> user.SeniorShare
	11, // 3: user.SeniorShare.user:type_name -> user.ShareUser
	0,  // 4: user.User.Login:input_type -> user.LoginReq
	2,  // 5: user.User.GetUserInfo:input_type -> user.GetUserInfoReq
	6,  // 6: user.User.UpdateUserProfile:input_type -> user.UpdateUserProfileReq
	8,  // 7: user.User.GetSeniorShares:input_type -> user.GetSeniorSharesReq
	12, // 8: user.User.CreateSeniorShare:input_type -> user.CreateSeniorShareReq
	14, // 9: user.User.LikeSeniorShare:input_type -> user.LikeSeniorShareReq
	16, // 10: user.User.CareerAssessment:input_type -> user.CareerAssessmentReq
	18, // 11: user.User.GetSubjectPlan:input_type -> user.GetSubjectPlanReq
	1,  // 12: user.User.Login:output_type -> user.LoginResp
	3,  // 13: user.User.GetUserInfo:output_type -> user.GetUserInfoResp
	7,  // 14: user.User.UpdateUserProfile:output_type -> user.UpdateUserProfileResp
	9,  // 15: user.User.GetSeniorShares:output_type -> user.GetSeniorSharesResp
	13, // 16: user.User.CreateSeniorShare:output_type -> user.CreateSeniorShareResp
	15, // 17: user.User.LikeSeniorShare:output_type -> user.LikeSeniorShareResp
	17, // 18: user.User.CareerAssessment:output_type -> user.CareerAssessmentResp
	19, // 19: user.User.GetSubjectPlan:output_type -> user.GetSubjectPlanResp
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_app_user_rpc_user_proto_init() }
func file_app_user_rpc_user_proto_init() {
	if File_app_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_user_rpc_user_proto_rawDesc), len(file_app_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_app_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_app_user_rpc_user_proto_msgTypes,
	}.Build()
	File_app_user_rpc_user_proto = out.File
	file_app_user_rpc_user_proto_goTypes = nil
	file_app_user_rpc_user_proto_depIdxs = nil
}
