// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: app/user/rpc/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_Login_FullMethodName             = "/user.User/Login"
	User_GetUserInfo_FullMethodName       = "/user.User/GetUserInfo"
	User_UpdateUserProfile_FullMethodName = "/user.User/UpdateUserProfile"
	User_GetSeniorShares_FullMethodName   = "/user.User/GetSeniorShares"
	User_CreateSeniorShare_FullMethodName = "/user.User/CreateSeniorShare"
	User_LikeSeniorShare_FullMethodName   = "/user.User/LikeSeniorShare"
	User_CareerAssessment_FullMethodName  = "/user.User/CareerAssessment"
	User_GetSubjectPlan_FullMethodName    = "/user.User/GetSubjectPlan"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户服务
type UserClient interface {
	// 用户登录/注册
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	// 更新用户档案
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error)
	// 获取学长分享列表
	GetSeniorShares(ctx context.Context, in *GetSeniorSharesReq, opts ...grpc.CallOption) (*GetSeniorSharesResp, error)
	// 创建学长分享
	CreateSeniorShare(ctx context.Context, in *CreateSeniorShareReq, opts ...grpc.CallOption) (*CreateSeniorShareResp, error)
	// 点赞/取消点赞分享
	LikeSeniorShare(ctx context.Context, in *LikeSeniorShareReq, opts ...grpc.CallOption) (*LikeSeniorShareResp, error)
	// 职业测评
	CareerAssessment(ctx context.Context, in *CareerAssessmentReq, opts ...grpc.CallOption) (*CareerAssessmentResp, error)
	// 获取选科规划
	GetSubjectPlan(ctx context.Context, in *GetSubjectPlanReq, opts ...grpc.CallOption) (*GetSubjectPlanResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, User_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, User_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserProfileResp)
	err := c.cc.Invoke(ctx, User_UpdateUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSeniorShares(ctx context.Context, in *GetSeniorSharesReq, opts ...grpc.CallOption) (*GetSeniorSharesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeniorSharesResp)
	err := c.cc.Invoke(ctx, User_GetSeniorShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateSeniorShare(ctx context.Context, in *CreateSeniorShareReq, opts ...grpc.CallOption) (*CreateSeniorShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSeniorShareResp)
	err := c.cc.Invoke(ctx, User_CreateSeniorShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) LikeSeniorShare(ctx context.Context, in *LikeSeniorShareReq, opts ...grpc.CallOption) (*LikeSeniorShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeSeniorShareResp)
	err := c.cc.Invoke(ctx, User_LikeSeniorShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CareerAssessment(ctx context.Context, in *CareerAssessmentReq, opts ...grpc.CallOption) (*CareerAssessmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CareerAssessmentResp)
	err := c.cc.Invoke(ctx, User_CareerAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSubjectPlan(ctx context.Context, in *GetSubjectPlanReq, opts ...grpc.CallOption) (*GetSubjectPlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubjectPlanResp)
	err := c.cc.Invoke(ctx, User_GetSubjectPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
//
// 用户服务
type UserServer interface {
	// 用户登录/注册
	Login(context.Context, *LoginReq) (*LoginResp, error)
	// 获取用户信息
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	// 更新用户档案
	UpdateUserProfile(context.Context, *UpdateUserProfileReq) (*UpdateUserProfileResp, error)
	// 获取学长分享列表
	GetSeniorShares(context.Context, *GetSeniorSharesReq) (*GetSeniorSharesResp, error)
	// 创建学长分享
	CreateSeniorShare(context.Context, *CreateSeniorShareReq) (*CreateSeniorShareResp, error)
	// 点赞/取消点赞分享
	LikeSeniorShare(context.Context, *LikeSeniorShareReq) (*LikeSeniorShareResp, error)
	// 职业测评
	CareerAssessment(context.Context, *CareerAssessmentReq) (*CareerAssessmentResp, error)
	// 获取选科规划
	GetSubjectPlan(context.Context, *GetSubjectPlanReq) (*GetSubjectPlanResp, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServer) UpdateUserProfile(context.Context, *UpdateUserProfileReq) (*UpdateUserProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (UnimplementedUserServer) GetSeniorShares(context.Context, *GetSeniorSharesReq) (*GetSeniorSharesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeniorShares not implemented")
}
func (UnimplementedUserServer) CreateSeniorShare(context.Context, *CreateSeniorShareReq) (*CreateSeniorShareResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeniorShare not implemented")
}
func (UnimplementedUserServer) LikeSeniorShare(context.Context, *LikeSeniorShareReq) (*LikeSeniorShareResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeSeniorShare not implemented")
}
func (UnimplementedUserServer) CareerAssessment(context.Context, *CareerAssessmentReq) (*CareerAssessmentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CareerAssessment not implemented")
}
func (UnimplementedUserServer) GetSubjectPlan(context.Context, *GetSubjectPlanReq) (*GetSubjectPlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubjectPlan not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserProfile(ctx, req.(*UpdateUserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSeniorShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeniorSharesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSeniorShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetSeniorShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSeniorShares(ctx, req.(*GetSeniorSharesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateSeniorShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeniorShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateSeniorShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CreateSeniorShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateSeniorShare(ctx, req.(*CreateSeniorShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_LikeSeniorShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeSeniorShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).LikeSeniorShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_LikeSeniorShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).LikeSeniorShare(ctx, req.(*LikeSeniorShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CareerAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CareerAssessmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CareerAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CareerAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CareerAssessment(ctx, req.(*CareerAssessmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSubjectPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubjectPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSubjectPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetSubjectPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSubjectPlan(ctx, req.(*GetSubjectPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _User_UpdateUserProfile_Handler,
		},
		{
			MethodName: "GetSeniorShares",
			Handler:    _User_GetSeniorShares_Handler,
		},
		{
			MethodName: "CreateSeniorShare",
			Handler:    _User_CreateSeniorShare_Handler,
		},
		{
			MethodName: "LikeSeniorShare",
			Handler:    _User_LikeSeniorShare_Handler,
		},
		{
			MethodName: "CareerAssessment",
			Handler:    _User_CareerAssessment_Handler,
		},
		{
			MethodName: "GetSubjectPlan",
			Handler:    _User_GetSubjectPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/user/rpc/user.proto",
}
