// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: app/ai/rpc/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求和响应消息
type GenerateVolunteerSuggestionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      string                 `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType     int32                  `protobuf:"varint,2,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Subjects      string                 `protobuf:"bytes,5,opt,name=subjects,proto3" json:"subjects,omitempty"`
	InterestTags  []string               `protobuf:"bytes,6,rep,name=interest_tags,json=interestTags,proto3" json:"interest_tags,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateVolunteerSuggestionReq) Reset() {
	*x = GenerateVolunteerSuggestionReq{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVolunteerSuggestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVolunteerSuggestionReq) ProtoMessage() {}

func (x *GenerateVolunteerSuggestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVolunteerSuggestionReq.ProtoReflect.Descriptor instead.
func (*GenerateVolunteerSuggestionReq) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateVolunteerSuggestionReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GenerateVolunteerSuggestionReq) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *GenerateVolunteerSuggestionReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GenerateVolunteerSuggestionReq) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GenerateVolunteerSuggestionReq) GetSubjects() string {
	if x != nil {
		return x.Subjects
	}
	return ""
}

func (x *GenerateVolunteerSuggestionReq) GetInterestTags() []string {
	if x != nil {
		return x.InterestTags
	}
	return nil
}

func (x *GenerateVolunteerSuggestionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GenerateVolunteerSuggestionResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Categories      []*SuggestionCategory  `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	AnalysisSummary string                 `protobuf:"bytes,2,opt,name=analysis_summary,json=analysisSummary,proto3" json:"analysis_summary,omitempty"`
	Recommendations []string               `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	CacheKey        string                 `protobuf:"bytes,4,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateVolunteerSuggestionResp) Reset() {
	*x = GenerateVolunteerSuggestionResp{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVolunteerSuggestionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVolunteerSuggestionResp) ProtoMessage() {}

func (x *GenerateVolunteerSuggestionResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVolunteerSuggestionResp.ProtoReflect.Descriptor instead.
func (*GenerateVolunteerSuggestionResp) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateVolunteerSuggestionResp) GetCategories() []*SuggestionCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GenerateVolunteerSuggestionResp) GetAnalysisSummary() string {
	if x != nil {
		return x.AnalysisSummary
	}
	return ""
}

func (x *GenerateVolunteerSuggestionResp) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *GenerateVolunteerSuggestionResp) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

type SuggestionCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // 冲/稳/保
	Colleges      []*CollegeSuggestion   `protobuf:"bytes,2,rep,name=colleges,proto3" json:"colleges,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionCategory) Reset() {
	*x = SuggestionCategory{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionCategory) ProtoMessage() {}

func (x *SuggestionCategory) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionCategory.ProtoReflect.Descriptor instead.
func (*SuggestionCategory) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{2}
}

func (x *SuggestionCategory) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SuggestionCategory) GetColleges() []*CollegeSuggestion {
	if x != nil {
		return x.Colleges
	}
	return nil
}

func (x *SuggestionCategory) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CollegeSuggestion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollegeCode    string                 `protobuf:"bytes,1,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	CollegeName    string                 `protobuf:"bytes,2,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	MajorCode      string                 `protobuf:"bytes,3,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	MajorName      string                 `protobuf:"bytes,4,opt,name=major_name,json=majorName,proto3" json:"major_name,omitempty"`
	Batch          string                 `protobuf:"bytes,5,opt,name=batch,proto3" json:"batch,omitempty"`
	MinScore       int32                  `protobuf:"varint,6,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MinRank        int32                  `protobuf:"varint,7,opt,name=min_rank,json=minRank,proto3" json:"min_rank,omitempty"`
	Year           int32                  `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	MatchingScore  float64                `protobuf:"fixed64,9,opt,name=matching_score,json=matchingScore,proto3" json:"matching_score,omitempty"` // 匹配度评分 0-1
	Advantages     string                 `protobuf:"bytes,10,opt,name=advantages,proto3" json:"advantages,omitempty"`
	Considerations string                 `protobuf:"bytes,11,opt,name=considerations,proto3" json:"considerations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollegeSuggestion) Reset() {
	*x = CollegeSuggestion{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollegeSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollegeSuggestion) ProtoMessage() {}

func (x *CollegeSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollegeSuggestion.ProtoReflect.Descriptor instead.
func (*CollegeSuggestion) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{3}
}

func (x *CollegeSuggestion) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

func (x *CollegeSuggestion) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *CollegeSuggestion) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *CollegeSuggestion) GetMajorName() string {
	if x != nil {
		return x.MajorName
	}
	return ""
}

func (x *CollegeSuggestion) GetBatch() string {
	if x != nil {
		return x.Batch
	}
	return ""
}

func (x *CollegeSuggestion) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *CollegeSuggestion) GetMinRank() int32 {
	if x != nil {
		return x.MinRank
	}
	return 0
}

func (x *CollegeSuggestion) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CollegeSuggestion) GetMatchingScore() float64 {
	if x != nil {
		return x.MatchingScore
	}
	return 0
}

func (x *CollegeSuggestion) GetAdvantages() string {
	if x != nil {
		return x.Advantages
	}
	return ""
}

func (x *CollegeSuggestion) GetConsiderations() string {
	if x != nil {
		return x.Considerations
	}
	return ""
}

type GetVolunteerAdviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolunteerAdviceReq) Reset() {
	*x = GetVolunteerAdviceReq{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolunteerAdviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolunteerAdviceReq) ProtoMessage() {}

func (x *GetVolunteerAdviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolunteerAdviceReq.ProtoReflect.Descriptor instead.
func (*GetVolunteerAdviceReq) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{4}
}

func (x *GetVolunteerAdviceReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetVolunteerAdviceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetVolunteerAdviceReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetVolunteerAdviceReq) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetVolunteerAdviceResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Answer           string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sources          []string               `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	RelatedQuestions []*RelatedQuestion     `protobuf:"bytes,4,rep,name=related_questions,json=relatedQuestions,proto3" json:"related_questions,omitempty"`
	Confidence       string                 `protobuf:"bytes,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetVolunteerAdviceResp) Reset() {
	*x = GetVolunteerAdviceResp{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolunteerAdviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolunteerAdviceResp) ProtoMessage() {}

func (x *GetVolunteerAdviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolunteerAdviceResp.ProtoReflect.Descriptor instead.
func (*GetVolunteerAdviceResp) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GetVolunteerAdviceResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *GetVolunteerAdviceResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetVolunteerAdviceResp) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GetVolunteerAdviceResp) GetRelatedQuestions() []*RelatedQuestion {
	if x != nil {
		return x.RelatedQuestions
	}
	return nil
}

func (x *GetVolunteerAdviceResp) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

type RelatedQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	AnswerPreview string                 `protobuf:"bytes,2,opt,name=answer_preview,json=answerPreview,proto3" json:"answer_preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedQuestion) Reset() {
	*x = RelatedQuestion{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedQuestion) ProtoMessage() {}

func (x *RelatedQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedQuestion.ProtoReflect.Descriptor instead.
func (*RelatedQuestion) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{6}
}

func (x *RelatedQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *RelatedQuestion) GetAnswerPreview() string {
	if x != nil {
		return x.AnswerPreview
	}
	return ""
}

type AnalyzeUserProfileReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Province        string                 `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType       int32                  `protobuf:"varint,3,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	Score           int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Rank            int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	Subjects        string                 `protobuf:"bytes,6,opt,name=subjects,proto3" json:"subjects,omitempty"`
	InterestTags    []string               `protobuf:"bytes,7,rep,name=interest_tags,json=interestTags,proto3" json:"interest_tags,omitempty"`
	PersonalityType string                 `protobuf:"bytes,8,opt,name=personality_type,json=personalityType,proto3" json:"personality_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeUserProfileReq) Reset() {
	*x = AnalyzeUserProfileReq{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeUserProfileReq) ProtoMessage() {}

func (x *AnalyzeUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeUserProfileReq.ProtoReflect.Descriptor instead.
func (*AnalyzeUserProfileReq) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeUserProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnalyzeUserProfileReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AnalyzeUserProfileReq) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *AnalyzeUserProfileReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnalyzeUserProfileReq) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *AnalyzeUserProfileReq) GetSubjects() string {
	if x != nil {
		return x.Subjects
	}
	return ""
}

func (x *AnalyzeUserProfileReq) GetInterestTags() []string {
	if x != nil {
		return x.InterestTags
	}
	return nil
}

func (x *AnalyzeUserProfileReq) GetPersonalityType() string {
	if x != nil {
		return x.PersonalityType
	}
	return ""
}

type AnalyzeUserProfileResp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AcademicPotential      float64                `protobuf:"fixed64,1,opt,name=academic_potential,json=academicPotential,proto3" json:"academic_potential,omitempty"`              // 学术潜力 0-1
	RecommendedCategories  []string               `protobuf:"bytes,2,rep,name=recommended_categories,json=recommendedCategories,proto3" json:"recommended_categories,omitempty"`    // 推荐专业类别
	CareerDirections       []string               `protobuf:"bytes,3,rep,name=career_directions,json=careerDirections,proto3" json:"career_directions,omitempty"`                   // 职业发展方向
	DevelopmentSuggestions []string               `protobuf:"bytes,4,rep,name=development_suggestions,json=developmentSuggestions,proto3" json:"development_suggestions,omitempty"` // 发展建议
	ProfileSummary         string                 `protobuf:"bytes,5,opt,name=profile_summary,json=profileSummary,proto3" json:"profile_summary,omitempty"`                         // 画像总结
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AnalyzeUserProfileResp) Reset() {
	*x = AnalyzeUserProfileResp{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeUserProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeUserProfileResp) ProtoMessage() {}

func (x *AnalyzeUserProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeUserProfileResp.ProtoReflect.Descriptor instead.
func (*AnalyzeUserProfileResp) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeUserProfileResp) GetAcademicPotential() float64 {
	if x != nil {
		return x.AcademicPotential
	}
	return 0
}

func (x *AnalyzeUserProfileResp) GetRecommendedCategories() []string {
	if x != nil {
		return x.RecommendedCategories
	}
	return nil
}

func (x *AnalyzeUserProfileResp) GetCareerDirections() []string {
	if x != nil {
		return x.CareerDirections
	}
	return nil
}

func (x *AnalyzeUserProfileResp) GetDevelopmentSuggestions() []string {
	if x != nil {
		return x.DevelopmentSuggestions
	}
	return nil
}

func (x *AnalyzeUserProfileResp) GetProfileSummary() string {
	if x != nil {
		return x.ProfileSummary
	}
	return ""
}

type AnalyzeCareerInterestReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Answers        map[string]int32       `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 测评答案
	AssessmentType string                 `protobuf:"bytes,3,opt,name=assessment_type,json=assessmentType,proto3" json:"assessment_type,omitempty"`                                        // mbti, holland, etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeCareerInterestReq) Reset() {
	*x = AnalyzeCareerInterestReq{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCareerInterestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCareerInterestReq) ProtoMessage() {}

func (x *AnalyzeCareerInterestReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCareerInterestReq.ProtoReflect.Descriptor instead.
func (*AnalyzeCareerInterestReq) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{9}
}

func (x *AnalyzeCareerInterestReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnalyzeCareerInterestReq) GetAnswers() map[string]int32 {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *AnalyzeCareerInterestReq) GetAssessmentType() string {
	if x != nil {
		return x.AssessmentType
	}
	return ""
}

type AnalyzeCareerInterestResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResultType        string                 `protobuf:"bytes,1,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	DimensionScores   map[string]float64     `protobuf:"bytes,2,rep,name=dimension_scores,json=dimensionScores,proto3" json:"dimension_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 各维度得分
	SuitableMajors    []string               `protobuf:"bytes,3,rep,name=suitable_majors,json=suitableMajors,proto3" json:"suitable_majors,omitempty"`                                                                                // 适合的专业
	SuitableCareers   []string               `protobuf:"bytes,4,rep,name=suitable_careers,json=suitableCareers,proto3" json:"suitable_careers,omitempty"`                                                                             // 适合的职业
	AnalysisReport    string                 `protobuf:"bytes,5,opt,name=analysis_report,json=analysisReport,proto3" json:"analysis_report,omitempty"`                                                                                // 分析报告
	DevelopmentAdvice []string               `protobuf:"bytes,6,rep,name=development_advice,json=developmentAdvice,proto3" json:"development_advice,omitempty"`                                                                       // 发展建议
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnalyzeCareerInterestResp) Reset() {
	*x = AnalyzeCareerInterestResp{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCareerInterestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCareerInterestResp) ProtoMessage() {}

func (x *AnalyzeCareerInterestResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCareerInterestResp.ProtoReflect.Descriptor instead.
func (*AnalyzeCareerInterestResp) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeCareerInterestResp) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *AnalyzeCareerInterestResp) GetDimensionScores() map[string]float64 {
	if x != nil {
		return x.DimensionScores
	}
	return nil
}

func (x *AnalyzeCareerInterestResp) GetSuitableMajors() []string {
	if x != nil {
		return x.SuitableMajors
	}
	return nil
}

func (x *AnalyzeCareerInterestResp) GetSuitableCareers() []string {
	if x != nil {
		return x.SuitableCareers
	}
	return nil
}

func (x *AnalyzeCareerInterestResp) GetAnalysisReport() string {
	if x != nil {
		return x.AnalysisReport
	}
	return ""
}

func (x *AnalyzeCareerInterestResp) GetDevelopmentAdvice() []string {
	if x != nil {
		return x.DevelopmentAdvice
	}
	return nil
}

type AnalyzeMajorMatchingReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MajorCode       string                 `protobuf:"bytes,2,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	InterestTags    []string               `protobuf:"bytes,3,rep,name=interest_tags,json=interestTags,proto3" json:"interest_tags,omitempty"`
	PersonalityType string                 `protobuf:"bytes,4,opt,name=personality_type,json=personalityType,proto3" json:"personality_type,omitempty"`
	CareerGoals     string                 `protobuf:"bytes,5,opt,name=career_goals,json=careerGoals,proto3" json:"career_goals,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeMajorMatchingReq) Reset() {
	*x = AnalyzeMajorMatchingReq{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMajorMatchingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMajorMatchingReq) ProtoMessage() {}

func (x *AnalyzeMajorMatchingReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMajorMatchingReq.ProtoReflect.Descriptor instead.
func (*AnalyzeMajorMatchingReq) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{11}
}

func (x *AnalyzeMajorMatchingReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnalyzeMajorMatchingReq) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *AnalyzeMajorMatchingReq) GetInterestTags() []string {
	if x != nil {
		return x.InterestTags
	}
	return nil
}

func (x *AnalyzeMajorMatchingReq) GetPersonalityType() string {
	if x != nil {
		return x.PersonalityType
	}
	return ""
}

func (x *AnalyzeMajorMatchingReq) GetCareerGoals() string {
	if x != nil {
		return x.CareerGoals
	}
	return ""
}

type AnalyzeMajorMatchingResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OverallMatching     float64                `protobuf:"fixed64,1,opt,name=overall_matching,json=overallMatching,proto3" json:"overall_matching,omitempty"`             // 整体匹配度 0-1
	InterestMatching    float64                `protobuf:"fixed64,2,opt,name=interest_matching,json=interestMatching,proto3" json:"interest_matching,omitempty"`          // 兴趣匹配度 0-1
	PersonalityMatching float64                `protobuf:"fixed64,3,opt,name=personality_matching,json=personalityMatching,proto3" json:"personality_matching,omitempty"` // 性格匹配度 0-1
	CareerMatching      float64                `protobuf:"fixed64,4,opt,name=career_matching,json=careerMatching,proto3" json:"career_matching,omitempty"`                // 职业匹配度 0-1
	MatchingPoints      []string               `protobuf:"bytes,5,rep,name=matching_points,json=matchingPoints,proto3" json:"matching_points,omitempty"`                  // 匹配要点
	Concerns            []string               `protobuf:"bytes,6,rep,name=concerns,proto3" json:"concerns,omitempty"`                                                    // 需注意事项
	Suggestions         []string               `protobuf:"bytes,7,rep,name=suggestions,proto3" json:"suggestions,omitempty"`                                              // 建议
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalyzeMajorMatchingResp) Reset() {
	*x = AnalyzeMajorMatchingResp{}
	mi := &file_app_ai_rpc_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMajorMatchingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMajorMatchingResp) ProtoMessage() {}

func (x *AnalyzeMajorMatchingResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_ai_rpc_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMajorMatchingResp.ProtoReflect.Descriptor instead.
func (*AnalyzeMajorMatchingResp) Descriptor() ([]byte, []int) {
	return file_app_ai_rpc_ai_proto_rawDescGZIP(), []int{12}
}

func (x *AnalyzeMajorMatchingResp) GetOverallMatching() float64 {
	if x != nil {
		return x.OverallMatching
	}
	return 0
}

func (x *AnalyzeMajorMatchingResp) GetInterestMatching() float64 {
	if x != nil {
		return x.InterestMatching
	}
	return 0
}

func (x *AnalyzeMajorMatchingResp) GetPersonalityMatching() float64 {
	if x != nil {
		return x.PersonalityMatching
	}
	return 0
}

func (x *AnalyzeMajorMatchingResp) GetCareerMatching() float64 {
	if x != nil {
		return x.CareerMatching
	}
	return 0
}

func (x *AnalyzeMajorMatchingResp) GetMatchingPoints() []string {
	if x != nil {
		return x.MatchingPoints
	}
	return nil
}

func (x *AnalyzeMajorMatchingResp) GetConcerns() []string {
	if x != nil {
		return x.Concerns
	}
	return nil
}

func (x *AnalyzeMajorMatchingResp) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_app_ai_rpc_ai_proto protoreflect.FileDescriptor

const file_app_ai_rpc_ai_proto_rawDesc = "" +
	"\n" +
	"\x13app/ai/rpc/ai.proto\x12\x02ai\"\xdf\x01\n" +
	"\x1eGenerateVolunteerSuggestionReq\x12\x1a\n" +
	"\bprovince\x18\x01 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x02 \x01(\x05R\tscoreType\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12\x1a\n" +
	"\bsubjects\x18\x05 \x01(\tR\bsubjects\x12#\n" +
	"\rinterest_tags\x18\x06 \x03(\tR\finterestTags\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\"\xcb\x01\n" +
	"\x1fGenerateVolunteerSuggestionResp\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.ai.SuggestionCategoryR\n" +
	"categories\x12)\n" +
	"\x10analysis_summary\x18\x02 \x01(\tR\x0fanalysisSummary\x12(\n" +
	"\x0frecommendations\x18\x03 \x03(\tR\x0frecommendations\x12\x1b\n" +
	"\tcache_key\x18\x04 \x01(\tR\bcacheKey\"{\n" +
	"\x12SuggestionCategory\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x121\n" +
	"\bcolleges\x18\x02 \x03(\v2\x15.ai.CollegeSuggestionR\bcolleges\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xe8\x02\n" +
	"\x11CollegeSuggestion\x12!\n" +
	"\fcollege_code\x18\x01 \x01(\tR\vcollegeCode\x12!\n" +
	"\fcollege_name\x18\x02 \x01(\tR\vcollegeName\x12\x1d\n" +
	"\n" +
	"major_code\x18\x03 \x01(\tR\tmajorCode\x12\x1d\n" +
	"\n" +
	"major_name\x18\x04 \x01(\tR\tmajorName\x12\x14\n" +
	"\x05batch\x18\x05 \x01(\tR\x05batch\x12\x1b\n" +
	"\tmin_score\x18\x06 \x01(\x05R\bminScore\x12\x19\n" +
	"\bmin_rank\x18\a \x01(\x05R\aminRank\x12\x12\n" +
	"\x04year\x18\b \x01(\x05R\x04year\x12%\n" +
	"\x0ematching_score\x18\t \x01(\x01R\rmatchingScore\x12\x1e\n" +
	"\n" +
	"advantages\x18\n" +
	" \x01(\tR\n" +
	"advantages\x12&\n" +
	"\x0econsiderations\x18\v \x01(\tR\x0econsiderations\"\xe3\x01\n" +
	"\x15GetVolunteerAdviceReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12@\n" +
	"\acontext\x18\x04 \x03(\v2&.ai.GetVolunteerAdviceReq.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x16GetVolunteerAdviceResp\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\asources\x18\x03 \x03(\tR\asources\x12@\n" +
	"\x11related_questions\x18\x04 \x03(\v2\x13.ai.RelatedQuestionR\x10relatedQuestions\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\tR\n" +
	"confidence\"T\n" +
	"\x0fRelatedQuestion\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12%\n" +
	"\x0eanswer_preview\x18\x02 \x01(\tR\ranswerPreview\"\x81\x02\n" +
	"\x15AnalyzeUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bprovince\x18\x02 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x03 \x01(\x05R\tscoreType\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12\x1a\n" +
	"\bsubjects\x18\x06 \x01(\tR\bsubjects\x12#\n" +
	"\rinterest_tags\x18\a \x03(\tR\finterestTags\x12)\n" +
	"\x10personality_type\x18\b \x01(\tR\x0fpersonalityType\"\x8d\x02\n" +
	"\x16AnalyzeUserProfileResp\x12-\n" +
	"\x12academic_potential\x18\x01 \x01(\x01R\x11academicPotential\x125\n" +
	"\x16recommended_categories\x18\x02 \x03(\tR\x15recommendedCategories\x12+\n" +
	"\x11career_directions\x18\x03 \x03(\tR\x10careerDirections\x127\n" +
	"\x17development_suggestions\x18\x04 \x03(\tR\x16developmentSuggestions\x12'\n" +
	"\x0fprofile_summary\x18\x05 \x01(\tR\x0eprofileSummary\"\xdd\x01\n" +
	"\x18AnalyzeCareerInterestReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12C\n" +
	"\aanswers\x18\x02 \x03(\v2).ai.AnalyzeCareerInterestReq.AnswersEntryR\aanswers\x12'\n" +
	"\x0fassessment_type\x18\x03 \x01(\tR\x0eassessmentType\x1a:\n" +
	"\fAnswersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x8b\x03\n" +
	"\x19AnalyzeCareerInterestResp\x12\x1f\n" +
	"\vresult_type\x18\x01 \x01(\tR\n" +
	"resultType\x12]\n" +
	"\x10dimension_scores\x18\x02 \x03(\v22.ai.AnalyzeCareerInterestResp.DimensionScoresEntryR\x0fdimensionScores\x12'\n" +
	"\x0fsuitable_majors\x18\x03 \x03(\tR\x0esuitableMajors\x12)\n" +
	"\x10suitable_careers\x18\x04 \x03(\tR\x0fsuitableCareers\x12'\n" +
	"\x0fanalysis_report\x18\x05 \x01(\tR\x0eanalysisReport\x12-\n" +
	"\x12development_advice\x18\x06 \x03(\tR\x11developmentAdvice\x1aB\n" +
	"\x14DimensionScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xc4\x01\n" +
	"\x17AnalyzeMajorMatchingReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"major_code\x18\x02 \x01(\tR\tmajorCode\x12#\n" +
	"\rinterest_tags\x18\x03 \x03(\tR\finterestTags\x12)\n" +
	"\x10personality_type\x18\x04 \x01(\tR\x0fpersonalityType\x12!\n" +
	"\fcareer_goals\x18\x05 \x01(\tR\vcareerGoals\"\xb5\x02\n" +
	"\x18AnalyzeMajorMatchingResp\x12)\n" +
	"\x10overall_matching\x18\x01 \x01(\x01R\x0foverallMatching\x12+\n" +
	"\x11interest_matching\x18\x02 \x01(\x01R\x10interestMatching\x121\n" +
	"\x14personality_matching\x18\x03 \x01(\x01R\x13personalityMatching\x12'\n" +
	"\x0fcareer_matching\x18\x04 \x01(\x01R\x0ecareerMatching\x12'\n" +
	"\x0fmatching_points\x18\x05 \x03(\tR\x0ematchingPoints\x12\x1a\n" +
	"\bconcerns\x18\x06 \x03(\tR\bconcerns\x12 \n" +
	"\vsuggestions\x18\a \x03(\tR\vsuggestions2\xaf\x03\n" +
	"\x02Ai\x12f\n" +
	"\x1bGenerateVolunteerSuggestion\x12\".ai.GenerateVolunteerSuggestionReq\x1a#.ai.GenerateVolunteerSuggestionResp\x12K\n" +
	"\x12GetVolunteerAdvice\x12\x19.ai.GetVolunteerAdviceReq\x1a\x1a.ai.GetVolunteerAdviceResp\x12K\n" +
	"\x12AnalyzeUserProfile\x12\x19.ai.AnalyzeUserProfileReq\x1a\x1a.ai.AnalyzeUserProfileResp\x12T\n" +
	"\x15AnalyzeCareerInterest\x12\x1c.ai.AnalyzeCareerInterestReq\x1a\x1d.ai.AnalyzeCareerInterestResp\x12Q\n" +
	"\x14AnalyzeMajorMatching\x12\x1b.ai.AnalyzeMajorMatchingReq\x1a\x1c.ai.AnalyzeMajorMatchingRespB$Z\"lighthouse-volunteer/app/ai/rpc/aib\x06proto3"

var (
	file_app_ai_rpc_ai_proto_rawDescOnce sync.Once
	file_app_ai_rpc_ai_proto_rawDescData []byte
)

func file_app_ai_rpc_ai_proto_rawDescGZIP() []byte {
	file_app_ai_rpc_ai_proto_rawDescOnce.Do(func() {
		file_app_ai_rpc_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_ai_rpc_ai_proto_rawDesc), len(file_app_ai_rpc_ai_proto_rawDesc)))
	})
	return file_app_ai_rpc_ai_proto_rawDescData
}

var file_app_ai_rpc_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_app_ai_rpc_ai_proto_goTypes = []any{
	(*GenerateVolunteerSuggestionReq)(nil),  // 0: ai.GenerateVolunteerSuggestionReq
	(*GenerateVolunteerSuggestionResp)(nil), // 1: ai.GenerateVolunteerSuggestionResp
	(*SuggestionCategory)(nil),              // 2: ai.SuggestionCategory
	(*CollegeSuggestion)(nil),               // 3: ai.CollegeSuggestion
	(*GetVolunteerAdviceReq)(nil),           // 4: ai.GetVolunteerAdviceReq
	(*GetVolunteerAdviceResp)(nil),          // 5: ai.GetVolunteerAdviceResp
	(*RelatedQuestion)(nil),                 // 6: ai.RelatedQuestion
	(*AnalyzeUserProfileReq)(nil),           // 7: ai.AnalyzeUserProfileReq
	(*AnalyzeUserProfileResp)(nil),          // 8: ai.AnalyzeUserProfileResp
	(*AnalyzeCareerInterestReq)(nil),        // 9: ai.AnalyzeCareerInterestReq
	(*AnalyzeCareerInterestResp)(nil),       // 10: ai.AnalyzeCareerInterestResp
	(*AnalyzeMajorMatchingReq)(nil),         // 11: ai.AnalyzeMajorMatchingReq
	(*AnalyzeMajorMatchingResp)(nil),        // 12: ai.AnalyzeMajorMatchingResp
	nil,                                     // 13: ai.GetVolunteerAdviceReq.ContextEntry
	nil,                                     // 14: ai.AnalyzeCareerInterestReq.AnswersEntry
	nil,                                     // 15: ai.AnalyzeCareerInterestResp.DimensionScoresEntry
}
var file_app_ai_rpc_ai_proto_depIdxs = []int32{
	2,  // 0: ai.GenerateVolunteerSuggestionResp.categories:type_name -> ai.SuggestionCategory
	3,  // 1: ai.SuggestionCategory.colleges:type_name -> ai.CollegeSuggestion
	13, // 2: ai.GetVolunteerAdviceReq.context:type_name -> ai.GetVolunteerAdviceReq.ContextEntry
	6,  // 3: ai.GetVolunteerAdviceResp.related_questions:type_name -> ai.RelatedQuestion
	14, // 4: ai.AnalyzeCareerInterestReq.answers:type_name -> ai.AnalyzeCareerInterestReq.AnswersEntry
	15, // 5: ai.AnalyzeCareerInterestResp.dimension_scores:type_name -> ai.AnalyzeCareerInterestResp.DimensionScoresEntry
	0,  // 6: ai.Ai.GenerateVolunteerSuggestion:input_type -> ai.GenerateVolunteerSuggestionReq
	4,  // 7: ai.Ai.GetVolunteerAdvice:input_type -> ai.GetVolunteerAdviceReq
	7,  // 8: ai.Ai.AnalyzeUserProfile:input_type -> ai.AnalyzeUserProfileReq
	9,  // 9: ai.Ai.AnalyzeCareerInterest:input_type -> ai.AnalyzeCareerInterestReq
	11, // 10: ai.Ai.AnalyzeMajorMatching:input_type -> ai.AnalyzeMajorMatchingReq
	1,  // 11: ai.Ai.GenerateVolunteerSuggestion:output_type -> ai.GenerateVolunteerSuggestionResp
	5,  // 12: ai.Ai.GetVolunteerAdvice:output_type -> ai.GetVolunteerAdviceResp
	8,  // 13: ai.Ai.AnalyzeUserProfile:output_type -> ai.AnalyzeUserProfileResp
	10, // 14: ai.Ai.AnalyzeCareerInterest:output_type -> ai.AnalyzeCareerInterestResp
	12, // 15: ai.Ai.AnalyzeMajorMatching:output_type -> ai.AnalyzeMajorMatchingResp
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_ai_rpc_ai_proto_init() }
func file_app_ai_rpc_ai_proto_init() {
	if File_app_ai_rpc_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_ai_rpc_ai_proto_rawDesc), len(file_app_ai_rpc_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_ai_rpc_ai_proto_goTypes,
		DependencyIndexes: file_app_ai_rpc_ai_proto_depIdxs,
		MessageInfos:      file_app_ai_rpc_ai_proto_msgTypes,
	}.Build()
	File_app_ai_rpc_ai_proto = out.File
	file_app_ai_rpc_ai_proto_goTypes = nil
	file_app_ai_rpc_ai_proto_depIdxs = nil
}
