// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: app/ai/rpc/ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ai_GenerateVolunteerSuggestion_FullMethodName = "/ai.Ai/GenerateVolunteerSuggestion"
	Ai_GetVolunteerAdvice_FullMethodName          = "/ai.Ai/GetVolunteerAdvice"
	Ai_AnalyzeUserProfile_FullMethodName          = "/ai.Ai/AnalyzeUserProfile"
	Ai_AnalyzeCareerInterest_FullMethodName       = "/ai.Ai/AnalyzeCareerInterest"
	Ai_AnalyzeMajorMatching_FullMethodName        = "/ai.Ai/AnalyzeMajorMatching"
)

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI分析服务
type AiClient interface {
	// 生成志愿推荐
	GenerateVolunteerSuggestion(ctx context.Context, in *GenerateVolunteerSuggestionReq, opts ...grpc.CallOption) (*GenerateVolunteerSuggestionResp, error)
	// AI志愿咨询
	GetVolunteerAdvice(ctx context.Context, in *GetVolunteerAdviceReq, opts ...grpc.CallOption) (*GetVolunteerAdviceResp, error)
	// 分析用户画像
	AnalyzeUserProfile(ctx context.Context, in *AnalyzeUserProfileReq, opts ...grpc.CallOption) (*AnalyzeUserProfileResp, error)
	// 职业兴趣分析
	AnalyzeCareerInterest(ctx context.Context, in *AnalyzeCareerInterestReq, opts ...grpc.CallOption) (*AnalyzeCareerInterestResp, error)
	// 专业匹配度分析
	AnalyzeMajorMatching(ctx context.Context, in *AnalyzeMajorMatchingReq, opts ...grpc.CallOption) (*AnalyzeMajorMatchingResp, error)
}

type aiClient struct {
	cc grpc.ClientConnInterface
}

func NewAiClient(cc grpc.ClientConnInterface) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) GenerateVolunteerSuggestion(ctx context.Context, in *GenerateVolunteerSuggestionReq, opts ...grpc.CallOption) (*GenerateVolunteerSuggestionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateVolunteerSuggestionResp)
	err := c.cc.Invoke(ctx, Ai_GenerateVolunteerSuggestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetVolunteerAdvice(ctx context.Context, in *GetVolunteerAdviceReq, opts ...grpc.CallOption) (*GetVolunteerAdviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolunteerAdviceResp)
	err := c.cc.Invoke(ctx, Ai_GetVolunteerAdvice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) AnalyzeUserProfile(ctx context.Context, in *AnalyzeUserProfileReq, opts ...grpc.CallOption) (*AnalyzeUserProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeUserProfileResp)
	err := c.cc.Invoke(ctx, Ai_AnalyzeUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) AnalyzeCareerInterest(ctx context.Context, in *AnalyzeCareerInterestReq, opts ...grpc.CallOption) (*AnalyzeCareerInterestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeCareerInterestResp)
	err := c.cc.Invoke(ctx, Ai_AnalyzeCareerInterest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) AnalyzeMajorMatching(ctx context.Context, in *AnalyzeMajorMatchingReq, opts ...grpc.CallOption) (*AnalyzeMajorMatchingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeMajorMatchingResp)
	err := c.cc.Invoke(ctx, Ai_AnalyzeMajorMatching_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
// All implementations must embed UnimplementedAiServer
// for forward compatibility.
//
// AI分析服务
type AiServer interface {
	// 生成志愿推荐
	GenerateVolunteerSuggestion(context.Context, *GenerateVolunteerSuggestionReq) (*GenerateVolunteerSuggestionResp, error)
	// AI志愿咨询
	GetVolunteerAdvice(context.Context, *GetVolunteerAdviceReq) (*GetVolunteerAdviceResp, error)
	// 分析用户画像
	AnalyzeUserProfile(context.Context, *AnalyzeUserProfileReq) (*AnalyzeUserProfileResp, error)
	// 职业兴趣分析
	AnalyzeCareerInterest(context.Context, *AnalyzeCareerInterestReq) (*AnalyzeCareerInterestResp, error)
	// 专业匹配度分析
	AnalyzeMajorMatching(context.Context, *AnalyzeMajorMatchingReq) (*AnalyzeMajorMatchingResp, error)
	mustEmbedUnimplementedAiServer()
}

// UnimplementedAiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServer struct{}

func (UnimplementedAiServer) GenerateVolunteerSuggestion(context.Context, *GenerateVolunteerSuggestionReq) (*GenerateVolunteerSuggestionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateVolunteerSuggestion not implemented")
}
func (UnimplementedAiServer) GetVolunteerAdvice(context.Context, *GetVolunteerAdviceReq) (*GetVolunteerAdviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolunteerAdvice not implemented")
}
func (UnimplementedAiServer) AnalyzeUserProfile(context.Context, *AnalyzeUserProfileReq) (*AnalyzeUserProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeUserProfile not implemented")
}
func (UnimplementedAiServer) AnalyzeCareerInterest(context.Context, *AnalyzeCareerInterestReq) (*AnalyzeCareerInterestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeCareerInterest not implemented")
}
func (UnimplementedAiServer) AnalyzeMajorMatching(context.Context, *AnalyzeMajorMatchingReq) (*AnalyzeMajorMatchingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeMajorMatching not implemented")
}
func (UnimplementedAiServer) mustEmbedUnimplementedAiServer() {}
func (UnimplementedAiServer) testEmbeddedByValue()            {}

// UnsafeAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServer will
// result in compilation errors.
type UnsafeAiServer interface {
	mustEmbedUnimplementedAiServer()
}

func RegisterAiServer(s grpc.ServiceRegistrar, srv AiServer) {
	// If the following call panics, it indicates UnimplementedAiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ai_ServiceDesc, srv)
}

func _Ai_GenerateVolunteerSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVolunteerSuggestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GenerateVolunteerSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GenerateVolunteerSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GenerateVolunteerSuggestion(ctx, req.(*GenerateVolunteerSuggestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetVolunteerAdvice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolunteerAdviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetVolunteerAdvice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetVolunteerAdvice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetVolunteerAdvice(ctx, req.(*GetVolunteerAdviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_AnalyzeUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeUserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).AnalyzeUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_AnalyzeUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).AnalyzeUserProfile(ctx, req.(*AnalyzeUserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_AnalyzeCareerInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeCareerInterestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).AnalyzeCareerInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_AnalyzeCareerInterest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).AnalyzeCareerInterest(ctx, req.(*AnalyzeCareerInterestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_AnalyzeMajorMatching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeMajorMatchingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).AnalyzeMajorMatching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_AnalyzeMajorMatching_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).AnalyzeMajorMatching(ctx, req.(*AnalyzeMajorMatchingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ai_ServiceDesc is the grpc.ServiceDesc for Ai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateVolunteerSuggestion",
			Handler:    _Ai_GenerateVolunteerSuggestion_Handler,
		},
		{
			MethodName: "GetVolunteerAdvice",
			Handler:    _Ai_GetVolunteerAdvice_Handler,
		},
		{
			MethodName: "AnalyzeUserProfile",
			Handler:    _Ai_AnalyzeUserProfile_Handler,
		},
		{
			MethodName: "AnalyzeCareerInterest",
			Handler:    _Ai_AnalyzeCareerInterest_Handler,
		},
		{
			MethodName: "AnalyzeMajorMatching",
			Handler:    _Ai_AnalyzeMajorMatching_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/ai/rpc/ai.proto",
}
