// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: user.proto

package userClient

import (
	"context"

	"lighthouse-volunteer/pb/lighthouse-volunteer/app/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CareerAssessmentReq   = user.CareerAssessmentReq
	CareerAssessmentResp  = user.CareerAssessmentResp
	CreateSeniorShareReq  = user.CreateSeniorShareReq
	CreateSeniorShareResp = user.CreateSeniorShareResp
	GetSeniorSharesReq    = user.GetSeniorSharesReq
	GetSeniorSharesResp   = user.GetSeniorSharesResp
	GetSubjectPlanReq     = user.GetSubjectPlanReq
	GetSubjectPlanResp    = user.GetSubjectPlanResp
	GetUserInfoReq        = user.GetUserInfoReq
	GetUserInfoResp       = user.GetUserInfoResp
	LikeSeniorShareReq    = user.LikeSeniorShareReq
	LikeSeniorShareResp   = user.LikeSeniorShareResp
	LoginReq              = user.LoginReq
	LoginResp             = user.LoginResp
	SeniorShare           = user.SeniorShare
	ShareUser             = user.ShareUser
	UpdateUserProfileReq  = user.UpdateUserProfileReq
	UpdateUserProfileResp = user.UpdateUserProfileResp
	UserInfo              = user.UserInfo
	UserProfile           = user.UserProfile

	User interface {
		// 用户登录/注册
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// 更新用户档案
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error)
		// 获取学长分享列表
		GetSeniorShares(ctx context.Context, in *GetSeniorSharesReq, opts ...grpc.CallOption) (*GetSeniorSharesResp, error)
		// 创建学长分享
		CreateSeniorShare(ctx context.Context, in *CreateSeniorShareReq, opts ...grpc.CallOption) (*CreateSeniorShareResp, error)
		// 点赞/取消点赞分享
		LikeSeniorShare(ctx context.Context, in *LikeSeniorShareReq, opts ...grpc.CallOption) (*LikeSeniorShareResp, error)
		// 职业测评
		CareerAssessment(ctx context.Context, in *CareerAssessmentReq, opts ...grpc.CallOption) (*CareerAssessmentResp, error)
		// 获取选科规划
		GetSubjectPlan(ctx context.Context, in *GetSubjectPlanReq, opts ...grpc.CallOption) (*GetSubjectPlanResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 用户登录/注册
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 更新用户档案
func (m *defaultUser) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserProfile(ctx, in, opts...)
}

// 获取学长分享列表
func (m *defaultUser) GetSeniorShares(ctx context.Context, in *GetSeniorSharesReq, opts ...grpc.CallOption) (*GetSeniorSharesResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetSeniorShares(ctx, in, opts...)
}

// 创建学长分享
func (m *defaultUser) CreateSeniorShare(ctx context.Context, in *CreateSeniorShareReq, opts ...grpc.CallOption) (*CreateSeniorShareResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateSeniorShare(ctx, in, opts...)
}

// 点赞/取消点赞分享
func (m *defaultUser) LikeSeniorShare(ctx context.Context, in *LikeSeniorShareReq, opts ...grpc.CallOption) (*LikeSeniorShareResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LikeSeniorShare(ctx, in, opts...)
}

// 职业测评
func (m *defaultUser) CareerAssessment(ctx context.Context, in *CareerAssessmentReq, opts ...grpc.CallOption) (*CareerAssessmentResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CareerAssessment(ctx, in, opts...)
}

// 获取选科规划
func (m *defaultUser) GetSubjectPlan(ctx context.Context, in *GetSubjectPlanReq, opts ...grpc.CallOption) (*GetSubjectPlanResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetSubjectPlan(ctx, in, opts...)
}
