// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package types

type AIChatRequest struct {
	UserId    string `json:"user_id,omitempty"`
	SessionId string `json:"session_id,omitempty"`
	Message   string `json:"message"`
	Context   string `json:"context,omitempty"` // 上下文信息
}

type AIChatResponse struct {
	Code      int    `json:"code"`
	Msg       string `json:"msg"`
	Reply     string `json:"reply"`
	SessionId string `json:"session_id"`
}

type AIRecRequest struct {
	Province  string `json:"province"`
	Subjects  string `json:"subjects"` // 选科，如"物理,化学,生物"
	Score     int    `json:"score"`
	Rank      int    `json:"rank"`
	Interests string `json:"interests,omitempty"` // 兴趣描述
}

type AIRecResponse struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data []Recommendation `json:"data"`
}

type AdmissionScore struct {
	Id          int64  `json:"id"`
	Year        int    `json:"year"`
	Province    string `json:"province"`
	CollegeName string `json:"college_name"`
	MajorName   string `json:"major_name,omitempty"`
	ScoreType   int    `json:"score_type"`
	Batch       string `json:"batch"`
	MinScore    int    `json:"min_score"`
	MinRank     int    `json:"min_rank"`
	DataSource  string `json:"data_source"`
}

type BaseResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CareerTestRequest struct {
	UserId   string                 `json:"user_id,omitempty"`
	Answers  map[string]interface{} `json:"answers"`   // 测评答案
	TestType string                 `json:"test_type"` // "holland", "mbti"等
}

type CareerTestResponse struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data CareerTestResult `json:"data"`
}

type CareerTestResult struct {
	UserId          string   `json:"user_id"`
	TestType        string   `json:"test_type"`
	Result          string   `json:"result"`
	Description     string   `json:"description"`
	Score           int      `json:"score"`
	RecommendMajors []string `json:"recommend_majors"`
	CreateTime      string   `json:"create_time"`
}

type ContentItem struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	AuthorId   int64  `json:"author_id"`
	AuthorName string `json:"author_name"`
	College    string `json:"college,omitempty"`
	Major      string `json:"major,omitempty"`
	Category   string `json:"category"`
	ViewCount  int    `json:"view_count"`
	LikeCount  int    `json:"like_count"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type EmptyRequest struct {
}

type GetContentRequest struct {
	Category string `json:"category,omitempty"` // "college", "major", "experience"
	College  string `json:"college,omitempty"`
	Major    string `json:"major,omitempty"`
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"page_size,default=20"`
}

type GetContentResponse struct {
	Code     int           `json:"code"`
	Msg      string        `json:"msg"`
	Data     []ContentItem `json:"data"`
	Total    int64         `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
}

type QueryScoreRequest struct {
	Year      int    `json:"year"`
	Province  string `json:"province"`
	College   string `json:"college,omitempty"`
	Major     string `json:"major,omitempty"`
	ScoreType int    `json:"score_type,omitempty"` // 1:文科, 2:理科, 3:综合改革
	Batch     string `json:"batch,omitempty"`
	MinScore  int    `json:"min_score,omitempty"`
	MaxScore  int    `json:"max_score,omitempty"`
}

type QueryScoreResponse struct {
	Code  int              `json:"code"`
	Msg   string           `json:"msg"`
	Data  []AdmissionScore `json:"data"`
	Total int64            `json:"total"`
}

type Recommendation struct {
	Level      string  `json:"level"` // "冲", "稳", "保"
	College    string  `json:"college"`
	Major      string  `json:"major"`
	MinRank    int     `json:"min_rank"`
	Reason     string  `json:"reason"`
	MatchScore float64 `json:"match_score"`
}
