// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: app/spider/rpc/spider.proto

package spider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求和响应消息
type GetSpiderTargetsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderTargetsReq) Reset() {
	*x = GetSpiderTargetsReq{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderTargetsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderTargetsReq) ProtoMessage() {}

func (x *GetSpiderTargetsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderTargetsReq.ProtoReflect.Descriptor instead.
func (*GetSpiderTargetsReq) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{0}
}

func (x *GetSpiderTargetsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSpiderTargetsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetSpiderTargetsReq) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *GetSpiderTargetsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetSpiderTargetsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*SpiderTarget        `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderTargetsResp) Reset() {
	*x = GetSpiderTargetsResp{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderTargetsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderTargetsResp) ProtoMessage() {}

func (x *GetSpiderTargetsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderTargetsResp.ProtoReflect.Descriptor instead.
func (*GetSpiderTargetsResp) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{1}
}

func (x *GetSpiderTargetsResp) GetTargets() []*SpiderTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *GetSpiderTargetsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SpiderTarget struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url            string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	DataType       string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	CrawlFrequency int32                  `protobuf:"varint,5,opt,name=crawl_frequency,json=crawlFrequency,proto3" json:"crawl_frequency,omitempty"`
	ParseRules     string                 `protobuf:"bytes,6,opt,name=parse_rules,json=parseRules,proto3" json:"parse_rules,omitempty"`
	LastCrawlTime  string                 `protobuf:"bytes,7,opt,name=last_crawl_time,json=lastCrawlTime,proto3" json:"last_crawl_time,omitempty"`
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpiderTarget) Reset() {
	*x = SpiderTarget{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpiderTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiderTarget) ProtoMessage() {}

func (x *SpiderTarget) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiderTarget.ProtoReflect.Descriptor instead.
func (*SpiderTarget) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{2}
}

func (x *SpiderTarget) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpiderTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpiderTarget) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SpiderTarget) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SpiderTarget) GetCrawlFrequency() int32 {
	if x != nil {
		return x.CrawlFrequency
	}
	return 0
}

func (x *SpiderTarget) GetParseRules() string {
	if x != nil {
		return x.ParseRules
	}
	return ""
}

func (x *SpiderTarget) GetLastCrawlTime() string {
	if x != nil {
		return x.LastCrawlTime
	}
	return ""
}

func (x *SpiderTarget) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SpiderTarget) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SpiderTarget) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateSpiderTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpiderTaskReq) Reset() {
	*x = CreateSpiderTaskReq{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpiderTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpiderTaskReq) ProtoMessage() {}

func (x *CreateSpiderTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpiderTaskReq.ProtoReflect.Descriptor instead.
func (*CreateSpiderTaskReq) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSpiderTaskReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CreateSpiderTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AsynqTaskId   string                 `protobuf:"bytes,2,opt,name=asynq_task_id,json=asynqTaskId,proto3" json:"asynq_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpiderTaskResp) Reset() {
	*x = CreateSpiderTaskResp{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpiderTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpiderTaskResp) ProtoMessage() {}

func (x *CreateSpiderTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpiderTaskResp.ProtoReflect.Descriptor instead.
func (*CreateSpiderTaskResp) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSpiderTaskResp) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateSpiderTaskResp) GetAsynqTaskId() string {
	if x != nil {
		return x.AsynqTaskId
	}
	return ""
}

type GetTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusReq) Reset() {
	*x = GetTaskStatusReq{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusReq) ProtoMessage() {}

func (x *GetTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusReq.ProtoReflect.Descriptor instead.
func (*GetTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskStatusReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetTaskStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *SpiderTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResp) Reset() {
	*x = GetTaskStatusResp{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResp) ProtoMessage() {}

func (x *GetTaskStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResp.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResp) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskStatusResp) GetTask() *SpiderTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type SpiderTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalItems    int32                  `protobuf:"varint,7,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,8,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpiderTask) Reset() {
	*x = SpiderTask{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpiderTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiderTask) ProtoMessage() {}

func (x *SpiderTask) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiderTask.ProtoReflect.Descriptor instead.
func (*SpiderTask) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{7}
}

func (x *SpiderTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpiderTask) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SpiderTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SpiderTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpiderTask) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SpiderTask) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *SpiderTask) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *SpiderTask) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SpiderTask) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SpiderTask) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SpiderTask) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CancelSpiderTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSpiderTaskReq) Reset() {
	*x = CancelSpiderTaskReq{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSpiderTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSpiderTaskReq) ProtoMessage() {}

func (x *CancelSpiderTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSpiderTaskReq.ProtoReflect.Descriptor instead.
func (*CancelSpiderTaskReq) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{8}
}

func (x *CancelSpiderTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type CancelSpiderTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSpiderTaskResp) Reset() {
	*x = CancelSpiderTaskResp{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSpiderTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSpiderTaskResp) ProtoMessage() {}

func (x *CancelSpiderTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSpiderTaskResp.ProtoReflect.Descriptor instead.
func (*CancelSpiderTaskResp) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{9}
}

func (x *CancelSpiderTaskResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSpiderResultsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderResultsReq) Reset() {
	*x = GetSpiderResultsReq{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderResultsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderResultsReq) ProtoMessage() {}

func (x *GetSpiderResultsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderResultsReq.ProtoReflect.Descriptor instead.
func (*GetSpiderResultsReq) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{10}
}

func (x *GetSpiderResultsReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetSpiderResultsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSpiderResultsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSpiderResultsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SpiderResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderResultsResp) Reset() {
	*x = GetSpiderResultsResp{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderResultsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderResultsResp) ProtoMessage() {}

func (x *GetSpiderResultsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderResultsResp.ProtoReflect.Descriptor instead.
func (*GetSpiderResultsResp) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{11}
}

func (x *GetSpiderResultsResp) GetResults() []*SpiderResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetSpiderResultsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SpiderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	RawData       string                 `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	ParsedData    string                 `protobuf:"bytes,5,opt,name=parsed_data,json=parsedData,proto3" json:"parsed_data,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpiderResult) Reset() {
	*x = SpiderResult{}
	mi := &file_app_spider_rpc_spider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpiderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiderResult) ProtoMessage() {}

func (x *SpiderResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_spider_rpc_spider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiderResult.ProtoReflect.Descriptor instead.
func (*SpiderResult) Descriptor() ([]byte, []int) {
	return file_app_spider_rpc_spider_proto_rawDescGZIP(), []int{12}
}

func (x *SpiderResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpiderResult) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SpiderResult) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SpiderResult) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *SpiderResult) GetParsedData() string {
	if x != nil {
		return x.ParsedData
	}
	return ""
}

func (x *SpiderResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SpiderResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SpiderResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_app_spider_rpc_spider_proto protoreflect.FileDescriptor

const file_app_spider_rpc_spider_proto_rawDesc = "" +
	"\n" +
	"\x1bapp/spider/rpc/spider.proto\x12\x06spider\"{\n" +
	"\x13GetSpiderTargetsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\\\n" +
	"\x14GetSpiderTargetsResp\x12.\n" +
	"\atargets\x18\x01 \x03(\v2\x14.spider.SpiderTargetR\atargets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa9\x02\n" +
	"\fSpiderTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12'\n" +
	"\x0fcrawl_frequency\x18\x05 \x01(\x05R\x0ecrawlFrequency\x12\x1f\n" +
	"\vparse_rules\x18\x06 \x01(\tR\n" +
	"parseRules\x12&\n" +
	"\x0flast_crawl_time\x18\a \x01(\tR\rlastCrawlTime\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"2\n" +
	"\x13CreateSpiderTaskReq\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\"S\n" +
	"\x14CreateSpiderTaskResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\"\n" +
	"\rasynq_task_id\x18\x02 \x01(\tR\vasynqTaskId\"+\n" +
	"\x10GetTaskStatusReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\";\n" +
	"\x11GetTaskStatusResp\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.spider.SpiderTaskR\x04task\"\xcd\x02\n" +
	"\n" +
	"SpiderTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1f\n" +
	"\vtotal_items\x18\a \x01(\x05R\n" +
	"totalItems\x12#\n" +
	"\rsuccess_count\x18\b \x01(\x05R\fsuccessCount\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\".\n" +
	"\x13CancelSpiderTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"0\n" +
	"\x14CancelSpiderTaskResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x13GetSpiderResultsReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\\\n" +
	"\x14GetSpiderResultsResp\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.spider.SpiderResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xec\x01\n" +
	"\fSpiderResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x19\n" +
	"\braw_data\x18\x04 \x01(\tR\arawData\x12\x1f\n" +
	"\vparsed_data\x18\x05 \x01(\tR\n" +
	"parsedData\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt2\x8a\x03\n" +
	"\x06Spider\x12M\n" +
	"\x10GetSpiderTargets\x12\x1b.spider.GetSpiderTargetsReq\x1a\x1c.spider.GetSpiderTargetsResp\x12M\n" +
	"\x10CreateSpiderTask\x12\x1b.spider.CreateSpiderTaskReq\x1a\x1c.spider.CreateSpiderTaskResp\x12D\n" +
	"\rGetTaskStatus\x12\x18.spider.GetTaskStatusReq\x1a\x19.spider.GetTaskStatusResp\x12M\n" +
	"\x10CancelSpiderTask\x12\x1b.spider.CancelSpiderTaskReq\x1a\x1c.spider.CancelSpiderTaskResp\x12M\n" +
	"\x10GetSpiderResults\x12\x1b.spider.GetSpiderResultsReq\x1a\x1c.spider.GetSpiderResultsRespB,Z*lighthouse-volunteer/app/spider/rpc/spiderb\x06proto3"

var (
	file_app_spider_rpc_spider_proto_rawDescOnce sync.Once
	file_app_spider_rpc_spider_proto_rawDescData []byte
)

func file_app_spider_rpc_spider_proto_rawDescGZIP() []byte {
	file_app_spider_rpc_spider_proto_rawDescOnce.Do(func() {
		file_app_spider_rpc_spider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_spider_rpc_spider_proto_rawDesc), len(file_app_spider_rpc_spider_proto_rawDesc)))
	})
	return file_app_spider_rpc_spider_proto_rawDescData
}

var file_app_spider_rpc_spider_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_app_spider_rpc_spider_proto_goTypes = []any{
	(*GetSpiderTargetsReq)(nil),  // 0: spider.GetSpiderTargetsReq
	(*GetSpiderTargetsResp)(nil), // 1: spider.GetSpiderTargetsResp
	(*SpiderTarget)(nil),         // 2: spider.SpiderTarget
	(*CreateSpiderTaskReq)(nil),  // 3: spider.CreateSpiderTaskReq
	(*CreateSpiderTaskResp)(nil), // 4: spider.CreateSpiderTaskResp
	(*GetTaskStatusReq)(nil),     // 5: spider.GetTaskStatusReq
	(*GetTaskStatusResp)(nil),    // 6: spider.GetTaskStatusResp
	(*SpiderTask)(nil),           // 7: spider.SpiderTask
	(*CancelSpiderTaskReq)(nil),  // 8: spider.CancelSpiderTaskReq
	(*CancelSpiderTaskResp)(nil), // 9: spider.CancelSpiderTaskResp
	(*GetSpiderResultsReq)(nil),  // 10: spider.GetSpiderResultsReq
	(*GetSpiderResultsResp)(nil), // 11: spider.GetSpiderResultsResp
	(*SpiderResult)(nil),         // 12: spider.SpiderResult
}
var file_app_spider_rpc_spider_proto_depIdxs = []int32{
	2,  // 0: spider.GetSpiderTargetsResp.targets:type_name -> spider.SpiderTarget
	7,  // 1: spider.GetTaskStatusResp.task:type_name -> spider.SpiderTask
	12, // 2: spider.GetSpiderResultsResp.results:type_name -> spider.SpiderResult
	0,  // 3: spider.Spider.GetSpiderTargets:input_type -> spider.GetSpiderTargetsReq
	3,  // 4: spider.Spider.CreateSpiderTask:input_type -> spider.CreateSpiderTaskReq
	5,  // 5: spider.Spider.GetTaskStatus:input_type -> spider.GetTaskStatusReq
	8,  // 6: spider.Spider.CancelSpiderTask:input_type -> spider.CancelSpiderTaskReq
	10, // 7: spider.Spider.GetSpiderResults:input_type -> spider.GetSpiderResultsReq
	1,  // 8: spider.Spider.GetSpiderTargets:output_type -> spider.GetSpiderTargetsResp
	4,  // 9: spider.Spider.CreateSpiderTask:output_type -> spider.CreateSpiderTaskResp
	6,  // 10: spider.Spider.GetTaskStatus:output_type -> spider.GetTaskStatusResp
	9,  // 11: spider.Spider.CancelSpiderTask:output_type -> spider.CancelSpiderTaskResp
	11, // 12: spider.Spider.GetSpiderResults:output_type -> spider.GetSpiderResultsResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_app_spider_rpc_spider_proto_init() }
func file_app_spider_rpc_spider_proto_init() {
	if File_app_spider_rpc_spider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_spider_rpc_spider_proto_rawDesc), len(file_app_spider_rpc_spider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_spider_rpc_spider_proto_goTypes,
		DependencyIndexes: file_app_spider_rpc_spider_proto_depIdxs,
		MessageInfos:      file_app_spider_rpc_spider_proto_msgTypes,
	}.Build()
	File_app_spider_rpc_spider_proto = out.File
	file_app_spider_rpc_spider_proto_goTypes = nil
	file_app_spider_rpc_spider_proto_depIdxs = nil
}
