// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: app/spider/rpc/spider.proto

package spider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Spider_GetSpiderTargets_FullMethodName = "/spider.Spider/GetSpiderTargets"
	Spider_CreateSpiderTask_FullMethodName = "/spider.Spider/CreateSpiderTask"
	Spider_GetTaskStatus_FullMethodName    = "/spider.Spider/GetTaskStatus"
	Spider_CancelSpiderTask_FullMethodName = "/spider.Spider/CancelSpiderTask"
	Spider_GetSpiderResults_FullMethodName = "/spider.Spider/GetSpiderResults"
)

// SpiderClient is the client API for Spider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 爬虫服务
type SpiderClient interface {
	// 获取爬虫目标列表
	GetSpiderTargets(ctx context.Context, in *GetSpiderTargetsReq, opts ...grpc.CallOption) (*GetSpiderTargetsResp, error)
	// 创建爬虫任务
	CreateSpiderTask(ctx context.Context, in *CreateSpiderTaskReq, opts ...grpc.CallOption) (*CreateSpiderTaskResp, error)
	// 获取任务状态
	GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusResp, error)
	// 取消爬虫任务
	CancelSpiderTask(ctx context.Context, in *CancelSpiderTaskReq, opts ...grpc.CallOption) (*CancelSpiderTaskResp, error)
	// 获取爬取结果
	GetSpiderResults(ctx context.Context, in *GetSpiderResultsReq, opts ...grpc.CallOption) (*GetSpiderResultsResp, error)
}

type spiderClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderClient(cc grpc.ClientConnInterface) SpiderClient {
	return &spiderClient{cc}
}

func (c *spiderClient) GetSpiderTargets(ctx context.Context, in *GetSpiderTargetsReq, opts ...grpc.CallOption) (*GetSpiderTargetsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpiderTargetsResp)
	err := c.cc.Invoke(ctx, Spider_GetSpiderTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) CreateSpiderTask(ctx context.Context, in *CreateSpiderTaskReq, opts ...grpc.CallOption) (*CreateSpiderTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSpiderTaskResp)
	err := c.cc.Invoke(ctx, Spider_CreateSpiderTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusResp)
	err := c.cc.Invoke(ctx, Spider_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) CancelSpiderTask(ctx context.Context, in *CancelSpiderTaskReq, opts ...grpc.CallOption) (*CancelSpiderTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelSpiderTaskResp)
	err := c.cc.Invoke(ctx, Spider_CancelSpiderTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) GetSpiderResults(ctx context.Context, in *GetSpiderResultsReq, opts ...grpc.CallOption) (*GetSpiderResultsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpiderResultsResp)
	err := c.cc.Invoke(ctx, Spider_GetSpiderResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiderServer is the server API for Spider service.
// All implementations must embed UnimplementedSpiderServer
// for forward compatibility.
//
// 爬虫服务
type SpiderServer interface {
	// 获取爬虫目标列表
	GetSpiderTargets(context.Context, *GetSpiderTargetsReq) (*GetSpiderTargetsResp, error)
	// 创建爬虫任务
	CreateSpiderTask(context.Context, *CreateSpiderTaskReq) (*CreateSpiderTaskResp, error)
	// 获取任务状态
	GetTaskStatus(context.Context, *GetTaskStatusReq) (*GetTaskStatusResp, error)
	// 取消爬虫任务
	CancelSpiderTask(context.Context, *CancelSpiderTaskReq) (*CancelSpiderTaskResp, error)
	// 获取爬取结果
	GetSpiderResults(context.Context, *GetSpiderResultsReq) (*GetSpiderResultsResp, error)
	mustEmbedUnimplementedSpiderServer()
}

// UnimplementedSpiderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpiderServer struct{}

func (UnimplementedSpiderServer) GetSpiderTargets(context.Context, *GetSpiderTargetsReq) (*GetSpiderTargetsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpiderTargets not implemented")
}
func (UnimplementedSpiderServer) CreateSpiderTask(context.Context, *CreateSpiderTaskReq) (*CreateSpiderTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpiderTask not implemented")
}
func (UnimplementedSpiderServer) GetTaskStatus(context.Context, *GetTaskStatusReq) (*GetTaskStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedSpiderServer) CancelSpiderTask(context.Context, *CancelSpiderTaskReq) (*CancelSpiderTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSpiderTask not implemented")
}
func (UnimplementedSpiderServer) GetSpiderResults(context.Context, *GetSpiderResultsReq) (*GetSpiderResultsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpiderResults not implemented")
}
func (UnimplementedSpiderServer) mustEmbedUnimplementedSpiderServer() {}
func (UnimplementedSpiderServer) testEmbeddedByValue()                {}

// UnsafeSpiderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiderServer will
// result in compilation errors.
type UnsafeSpiderServer interface {
	mustEmbedUnimplementedSpiderServer()
}

func RegisterSpiderServer(s grpc.ServiceRegistrar, srv SpiderServer) {
	// If the following call panics, it indicates UnimplementedSpiderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Spider_ServiceDesc, srv)
}

func _Spider_GetSpiderTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpiderTargetsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetSpiderTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_GetSpiderTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetSpiderTargets(ctx, req.(*GetSpiderTargetsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_CreateSpiderTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpiderTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).CreateSpiderTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_CreateSpiderTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).CreateSpiderTask(ctx, req.(*CreateSpiderTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetTaskStatus(ctx, req.(*GetTaskStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_CancelSpiderTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSpiderTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).CancelSpiderTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_CancelSpiderTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).CancelSpiderTask(ctx, req.(*CancelSpiderTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_GetSpiderResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpiderResultsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetSpiderResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_GetSpiderResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetSpiderResults(ctx, req.(*GetSpiderResultsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Spider_ServiceDesc is the grpc.ServiceDesc for Spider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spider.Spider",
	HandlerType: (*SpiderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpiderTargets",
			Handler:    _Spider_GetSpiderTargets_Handler,
		},
		{
			MethodName: "CreateSpiderTask",
			Handler:    _Spider_CreateSpiderTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _Spider_GetTaskStatus_Handler,
		},
		{
			MethodName: "CancelSpiderTask",
			Handler:    _Spider_CancelSpiderTask_Handler,
		},
		{
			MethodName: "GetSpiderResults",
			Handler:    _Spider_GetSpiderResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/spider/rpc/spider.proto",
}
