// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: app/score/rpc/score.proto

package score

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Score_QueryAdmissionScores_FullMethodName = "/score.Score/QueryAdmissionScores"
	Score_GetCollegeInfo_FullMethodName       = "/score.Score/GetCollegeInfo"
	Score_BatchGetCollegeInfo_FullMethodName  = "/score.Score/BatchGetCollegeInfo"
	Score_GetMajorInfo_FullMethodName         = "/score.Score/GetMajorInfo"
	Score_BatchGetMajorInfo_FullMethodName    = "/score.Score/BatchGetMajorInfo"
	Score_GetScoreTrend_FullMethodName        = "/score.Score/GetScoreTrend"
	Score_GetRankToScore_FullMethodName       = "/score.Score/GetRankToScore"
)

// ScoreClient is the client API for Score service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 数据查询服务
type ScoreClient interface {
	// 查询录取分数线
	QueryAdmissionScores(ctx context.Context, in *QueryAdmissionScoresReq, opts ...grpc.CallOption) (*QueryAdmissionScoresResp, error)
	// 获取学校信息
	GetCollegeInfo(ctx context.Context, in *GetCollegeInfoReq, opts ...grpc.CallOption) (*GetCollegeInfoResp, error)
	// 批量获取学校信息
	BatchGetCollegeInfo(ctx context.Context, in *BatchGetCollegeInfoReq, opts ...grpc.CallOption) (*BatchGetCollegeInfoResp, error)
	// 获取专业信息
	GetMajorInfo(ctx context.Context, in *GetMajorInfoReq, opts ...grpc.CallOption) (*GetMajorInfoResp, error)
	// 批量获取专业信息
	BatchGetMajorInfo(ctx context.Context, in *BatchGetMajorInfoReq, opts ...grpc.CallOption) (*BatchGetMajorInfoResp, error)
	// 获取分数线趋势
	GetScoreTrend(ctx context.Context, in *GetScoreTrendReq, opts ...grpc.CallOption) (*GetScoreTrendResp, error)
	// 获取位次对应的分数
	GetRankToScore(ctx context.Context, in *GetRankToScoreReq, opts ...grpc.CallOption) (*GetRankToScoreResp, error)
}

type scoreClient struct {
	cc grpc.ClientConnInterface
}

func NewScoreClient(cc grpc.ClientConnInterface) ScoreClient {
	return &scoreClient{cc}
}

func (c *scoreClient) QueryAdmissionScores(ctx context.Context, in *QueryAdmissionScoresReq, opts ...grpc.CallOption) (*QueryAdmissionScoresResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAdmissionScoresResp)
	err := c.cc.Invoke(ctx, Score_QueryAdmissionScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreClient) GetCollegeInfo(ctx context.Context, in *GetCollegeInfoReq, opts ...grpc.CallOption) (*GetCollegeInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollegeInfoResp)
	err := c.cc.Invoke(ctx, Score_GetCollegeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreClient) BatchGetCollegeInfo(ctx context.Context, in *BatchGetCollegeInfoReq, opts ...grpc.CallOption) (*BatchGetCollegeInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetCollegeInfoResp)
	err := c.cc.Invoke(ctx, Score_BatchGetCollegeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreClient) GetMajorInfo(ctx context.Context, in *GetMajorInfoReq, opts ...grpc.CallOption) (*GetMajorInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMajorInfoResp)
	err := c.cc.Invoke(ctx, Score_GetMajorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreClient) BatchGetMajorInfo(ctx context.Context, in *BatchGetMajorInfoReq, opts ...grpc.CallOption) (*BatchGetMajorInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetMajorInfoResp)
	err := c.cc.Invoke(ctx, Score_BatchGetMajorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreClient) GetScoreTrend(ctx context.Context, in *GetScoreTrendReq, opts ...grpc.CallOption) (*GetScoreTrendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScoreTrendResp)
	err := c.cc.Invoke(ctx, Score_GetScoreTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreClient) GetRankToScore(ctx context.Context, in *GetRankToScoreReq, opts ...grpc.CallOption) (*GetRankToScoreResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRankToScoreResp)
	err := c.cc.Invoke(ctx, Score_GetRankToScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoreServer is the server API for Score service.
// All implementations must embed UnimplementedScoreServer
// for forward compatibility.
//
// 数据查询服务
type ScoreServer interface {
	// 查询录取分数线
	QueryAdmissionScores(context.Context, *QueryAdmissionScoresReq) (*QueryAdmissionScoresResp, error)
	// 获取学校信息
	GetCollegeInfo(context.Context, *GetCollegeInfoReq) (*GetCollegeInfoResp, error)
	// 批量获取学校信息
	BatchGetCollegeInfo(context.Context, *BatchGetCollegeInfoReq) (*BatchGetCollegeInfoResp, error)
	// 获取专业信息
	GetMajorInfo(context.Context, *GetMajorInfoReq) (*GetMajorInfoResp, error)
	// 批量获取专业信息
	BatchGetMajorInfo(context.Context, *BatchGetMajorInfoReq) (*BatchGetMajorInfoResp, error)
	// 获取分数线趋势
	GetScoreTrend(context.Context, *GetScoreTrendReq) (*GetScoreTrendResp, error)
	// 获取位次对应的分数
	GetRankToScore(context.Context, *GetRankToScoreReq) (*GetRankToScoreResp, error)
	mustEmbedUnimplementedScoreServer()
}

// UnimplementedScoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScoreServer struct{}

func (UnimplementedScoreServer) QueryAdmissionScores(context.Context, *QueryAdmissionScoresReq) (*QueryAdmissionScoresResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAdmissionScores not implemented")
}
func (UnimplementedScoreServer) GetCollegeInfo(context.Context, *GetCollegeInfoReq) (*GetCollegeInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollegeInfo not implemented")
}
func (UnimplementedScoreServer) BatchGetCollegeInfo(context.Context, *BatchGetCollegeInfoReq) (*BatchGetCollegeInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetCollegeInfo not implemented")
}
func (UnimplementedScoreServer) GetMajorInfo(context.Context, *GetMajorInfoReq) (*GetMajorInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMajorInfo not implemented")
}
func (UnimplementedScoreServer) BatchGetMajorInfo(context.Context, *BatchGetMajorInfoReq) (*BatchGetMajorInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetMajorInfo not implemented")
}
func (UnimplementedScoreServer) GetScoreTrend(context.Context, *GetScoreTrendReq) (*GetScoreTrendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScoreTrend not implemented")
}
func (UnimplementedScoreServer) GetRankToScore(context.Context, *GetRankToScoreReq) (*GetRankToScoreResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRankToScore not implemented")
}
func (UnimplementedScoreServer) mustEmbedUnimplementedScoreServer() {}
func (UnimplementedScoreServer) testEmbeddedByValue()               {}

// UnsafeScoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoreServer will
// result in compilation errors.
type UnsafeScoreServer interface {
	mustEmbedUnimplementedScoreServer()
}

func RegisterScoreServer(s grpc.ServiceRegistrar, srv ScoreServer) {
	// If the following call panics, it indicates UnimplementedScoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Score_ServiceDesc, srv)
}

func _Score_QueryAdmissionScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAdmissionScoresReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServer).QueryAdmissionScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Score_QueryAdmissionScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServer).QueryAdmissionScores(ctx, req.(*QueryAdmissionScoresReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Score_GetCollegeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollegeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServer).GetCollegeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Score_GetCollegeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServer).GetCollegeInfo(ctx, req.(*GetCollegeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Score_BatchGetCollegeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCollegeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServer).BatchGetCollegeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Score_BatchGetCollegeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServer).BatchGetCollegeInfo(ctx, req.(*BatchGetCollegeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Score_GetMajorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMajorInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServer).GetMajorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Score_GetMajorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServer).GetMajorInfo(ctx, req.(*GetMajorInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Score_BatchGetMajorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetMajorInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServer).BatchGetMajorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Score_BatchGetMajorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServer).BatchGetMajorInfo(ctx, req.(*BatchGetMajorInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Score_GetScoreTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreTrendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServer).GetScoreTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Score_GetScoreTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServer).GetScoreTrend(ctx, req.(*GetScoreTrendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Score_GetRankToScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankToScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServer).GetRankToScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Score_GetRankToScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServer).GetRankToScore(ctx, req.(*GetRankToScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Score_ServiceDesc is the grpc.ServiceDesc for Score service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Score_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "score.Score",
	HandlerType: (*ScoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryAdmissionScores",
			Handler:    _Score_QueryAdmissionScores_Handler,
		},
		{
			MethodName: "GetCollegeInfo",
			Handler:    _Score_GetCollegeInfo_Handler,
		},
		{
			MethodName: "BatchGetCollegeInfo",
			Handler:    _Score_BatchGetCollegeInfo_Handler,
		},
		{
			MethodName: "GetMajorInfo",
			Handler:    _Score_GetMajorInfo_Handler,
		},
		{
			MethodName: "BatchGetMajorInfo",
			Handler:    _Score_BatchGetMajorInfo_Handler,
		},
		{
			MethodName: "GetScoreTrend",
			Handler:    _Score_GetScoreTrend_Handler,
		},
		{
			MethodName: "GetRankToScore",
			Handler:    _Score_GetRankToScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/score/rpc/score.proto",
}
