// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: app/score/rpc/score.proto

package score

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求和响应消息
type QueryAdmissionScoresReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      string                 `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType     int32                  `protobuf:"varint,2,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	MinScore      int32                  `protobuf:"varint,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	MinRank       int32                  `protobuf:"varint,5,opt,name=min_rank,json=minRank,proto3" json:"min_rank,omitempty"`
	MaxRank       int32                  `protobuf:"varint,6,opt,name=max_rank,json=maxRank,proto3" json:"max_rank,omitempty"`
	CollegeName   string                 `protobuf:"bytes,7,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	MajorName     string                 `protobuf:"bytes,8,opt,name=major_name,json=majorName,proto3" json:"major_name,omitempty"`
	Batch         string                 `protobuf:"bytes,9,opt,name=batch,proto3" json:"batch,omitempty"`
	Year          int32                  `protobuf:"varint,10,opt,name=year,proto3" json:"year,omitempty"`
	Page          int32                  `protobuf:"varint,11,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,12,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,13,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // score, rank, year
	SortOrder     string                 `protobuf:"bytes,14,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAdmissionScoresReq) Reset() {
	*x = QueryAdmissionScoresReq{}
	mi := &file_app_score_rpc_score_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAdmissionScoresReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAdmissionScoresReq) ProtoMessage() {}

func (x *QueryAdmissionScoresReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAdmissionScoresReq.ProtoReflect.Descriptor instead.
func (*QueryAdmissionScoresReq) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{0}
}

func (x *QueryAdmissionScoresReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *QueryAdmissionScoresReq) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetMinRank() int32 {
	if x != nil {
		return x.MinRank
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetMaxRank() int32 {
	if x != nil {
		return x.MaxRank
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *QueryAdmissionScoresReq) GetMajorName() string {
	if x != nil {
		return x.MajorName
	}
	return ""
}

func (x *QueryAdmissionScoresReq) GetBatch() string {
	if x != nil {
		return x.Batch
	}
	return ""
}

func (x *QueryAdmissionScoresReq) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryAdmissionScoresReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *QueryAdmissionScoresReq) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type QueryAdmissionScoresResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*AdmissionScore      `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAdmissionScoresResp) Reset() {
	*x = QueryAdmissionScoresResp{}
	mi := &file_app_score_rpc_score_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAdmissionScoresResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAdmissionScoresResp) ProtoMessage() {}

func (x *QueryAdmissionScoresResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAdmissionScoresResp.ProtoReflect.Descriptor instead.
func (*QueryAdmissionScoresResp) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{1}
}

func (x *QueryAdmissionScoresResp) GetScores() []*AdmissionScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *QueryAdmissionScoresResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryAdmissionScoresResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryAdmissionScoresResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdmissionScore struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year            int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Province        string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	CollegeCode     string                 `protobuf:"bytes,4,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	CollegeName     string                 `protobuf:"bytes,5,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	MajorCode       string                 `protobuf:"bytes,6,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	MajorName       string                 `protobuf:"bytes,7,opt,name=major_name,json=majorName,proto3" json:"major_name,omitempty"`
	Batch           string                 `protobuf:"bytes,8,opt,name=batch,proto3" json:"batch,omitempty"`
	ScoreType       int32                  `protobuf:"varint,9,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	MinScore        int32                  `protobuf:"varint,10,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MinRank         int32                  `protobuf:"varint,11,opt,name=min_rank,json=minRank,proto3" json:"min_rank,omitempty"`
	AvgScore        int32                  `protobuf:"varint,12,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	EnrollmentCount int32                  `protobuf:"varint,13,opt,name=enrollment_count,json=enrollmentCount,proto3" json:"enrollment_count,omitempty"`
	DataSource      string                 `protobuf:"bytes,14,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	DataQuality     int32                  `protobuf:"varint,15,opt,name=data_quality,json=dataQuality,proto3" json:"data_quality,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdmissionScore) Reset() {
	*x = AdmissionScore{}
	mi := &file_app_score_rpc_score_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionScore) ProtoMessage() {}

func (x *AdmissionScore) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionScore.ProtoReflect.Descriptor instead.
func (*AdmissionScore) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{2}
}

func (x *AdmissionScore) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdmissionScore) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AdmissionScore) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AdmissionScore) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

func (x *AdmissionScore) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *AdmissionScore) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *AdmissionScore) GetMajorName() string {
	if x != nil {
		return x.MajorName
	}
	return ""
}

func (x *AdmissionScore) GetBatch() string {
	if x != nil {
		return x.Batch
	}
	return ""
}

func (x *AdmissionScore) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *AdmissionScore) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *AdmissionScore) GetMinRank() int32 {
	if x != nil {
		return x.MinRank
	}
	return 0
}

func (x *AdmissionScore) GetAvgScore() int32 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *AdmissionScore) GetEnrollmentCount() int32 {
	if x != nil {
		return x.EnrollmentCount
	}
	return 0
}

func (x *AdmissionScore) GetDataSource() string {
	if x != nil {
		return x.DataSource
	}
	return ""
}

func (x *AdmissionScore) GetDataQuality() int32 {
	if x != nil {
		return x.DataQuality
	}
	return 0
}

func (x *AdmissionScore) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetCollegeInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollegeCode   string                 `protobuf:"bytes,1,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollegeInfoReq) Reset() {
	*x = GetCollegeInfoReq{}
	mi := &file_app_score_rpc_score_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollegeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollegeInfoReq) ProtoMessage() {}

func (x *GetCollegeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollegeInfoReq.ProtoReflect.Descriptor instead.
func (*GetCollegeInfoReq) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{3}
}

func (x *GetCollegeInfoReq) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

type GetCollegeInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	College       *CollegeInfo           `protobuf:"bytes,1,opt,name=college,proto3" json:"college,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollegeInfoResp) Reset() {
	*x = GetCollegeInfoResp{}
	mi := &file_app_score_rpc_score_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollegeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollegeInfoResp) ProtoMessage() {}

func (x *GetCollegeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollegeInfoResp.ProtoReflect.Descriptor instead.
func (*GetCollegeInfoResp) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{4}
}

func (x *GetCollegeInfoResp) GetCollege() *CollegeInfo {
	if x != nil {
		return x.College
	}
	return nil
}

type BatchGetCollegeInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollegeCodes  []string               `protobuf:"bytes,1,rep,name=college_codes,json=collegeCodes,proto3" json:"college_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetCollegeInfoReq) Reset() {
	*x = BatchGetCollegeInfoReq{}
	mi := &file_app_score_rpc_score_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetCollegeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCollegeInfoReq) ProtoMessage() {}

func (x *BatchGetCollegeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCollegeInfoReq.ProtoReflect.Descriptor instead.
func (*BatchGetCollegeInfoReq) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetCollegeInfoReq) GetCollegeCodes() []string {
	if x != nil {
		return x.CollegeCodes
	}
	return nil
}

type BatchGetCollegeInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Colleges      []*CollegeInfo         `protobuf:"bytes,1,rep,name=colleges,proto3" json:"colleges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetCollegeInfoResp) Reset() {
	*x = BatchGetCollegeInfoResp{}
	mi := &file_app_score_rpc_score_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetCollegeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCollegeInfoResp) ProtoMessage() {}

func (x *BatchGetCollegeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCollegeInfoResp.ProtoReflect.Descriptor instead.
func (*BatchGetCollegeInfoResp) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetCollegeInfoResp) GetColleges() []*CollegeInfo {
	if x != nil {
		return x.Colleges
	}
	return nil
}

type CollegeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CollegeCode    string                 `protobuf:"bytes,2,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	CollegeName    string                 `protobuf:"bytes,3,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	Province       string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City           string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Level          string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	Type           string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Nature         string                 `protobuf:"bytes,8,opt,name=nature,proto3" json:"nature,omitempty"`
	Website        string                 `protobuf:"bytes,9,opt,name=website,proto3" json:"website,omitempty"`
	Description    string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Ranking        int32                  `protobuf:"varint,11,opt,name=ranking,proto3" json:"ranking,omitempty"`
	EmploymentRate float64                `protobuf:"fixed64,12,opt,name=employment_rate,json=employmentRate,proto3" json:"employment_rate,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollegeInfo) Reset() {
	*x = CollegeInfo{}
	mi := &file_app_score_rpc_score_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollegeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollegeInfo) ProtoMessage() {}

func (x *CollegeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollegeInfo.ProtoReflect.Descriptor instead.
func (*CollegeInfo) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{7}
}

func (x *CollegeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CollegeInfo) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

func (x *CollegeInfo) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *CollegeInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CollegeInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CollegeInfo) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CollegeInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CollegeInfo) GetNature() string {
	if x != nil {
		return x.Nature
	}
	return ""
}

func (x *CollegeInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CollegeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CollegeInfo) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *CollegeInfo) GetEmploymentRate() float64 {
	if x != nil {
		return x.EmploymentRate
	}
	return 0
}

func (x *CollegeInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetMajorInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MajorCode     string                 `protobuf:"bytes,1,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMajorInfoReq) Reset() {
	*x = GetMajorInfoReq{}
	mi := &file_app_score_rpc_score_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMajorInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMajorInfoReq) ProtoMessage() {}

func (x *GetMajorInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMajorInfoReq.ProtoReflect.Descriptor instead.
func (*GetMajorInfoReq) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{8}
}

func (x *GetMajorInfoReq) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

type GetMajorInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         *MajorInfo             `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMajorInfoResp) Reset() {
	*x = GetMajorInfoResp{}
	mi := &file_app_score_rpc_score_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMajorInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMajorInfoResp) ProtoMessage() {}

func (x *GetMajorInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMajorInfoResp.ProtoReflect.Descriptor instead.
func (*GetMajorInfoResp) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{9}
}

func (x *GetMajorInfoResp) GetMajor() *MajorInfo {
	if x != nil {
		return x.Major
	}
	return nil
}

type BatchGetMajorInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MajorCodes    []string               `protobuf:"bytes,1,rep,name=major_codes,json=majorCodes,proto3" json:"major_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMajorInfoReq) Reset() {
	*x = BatchGetMajorInfoReq{}
	mi := &file_app_score_rpc_score_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMajorInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMajorInfoReq) ProtoMessage() {}

func (x *BatchGetMajorInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMajorInfoReq.ProtoReflect.Descriptor instead.
func (*BatchGetMajorInfoReq) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetMajorInfoReq) GetMajorCodes() []string {
	if x != nil {
		return x.MajorCodes
	}
	return nil
}

type BatchGetMajorInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Majors        []*MajorInfo           `protobuf:"bytes,1,rep,name=majors,proto3" json:"majors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMajorInfoResp) Reset() {
	*x = BatchGetMajorInfoResp{}
	mi := &file_app_score_rpc_score_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMajorInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMajorInfoResp) ProtoMessage() {}

func (x *BatchGetMajorInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMajorInfoResp.ProtoReflect.Descriptor instead.
func (*BatchGetMajorInfoResp) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetMajorInfoResp) GetMajors() []*MajorInfo {
	if x != nil {
		return x.Majors
	}
	return nil
}

type MajorInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MajorCode           string                 `protobuf:"bytes,2,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	MajorName           string                 `protobuf:"bytes,3,opt,name=major_name,json=majorName,proto3" json:"major_name,omitempty"`
	Category            string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Subcategory         string                 `protobuf:"bytes,5,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	Degree              string                 `protobuf:"bytes,6,opt,name=degree,proto3" json:"degree,omitempty"`
	Duration            int32                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Description         string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	EmploymentDirection string                 `protobuf:"bytes,9,opt,name=employment_direction,json=employmentDirection,proto3" json:"employment_direction,omitempty"`
	SalaryRange         string                 `protobuf:"bytes,10,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	DemandLevel         string                 `protobuf:"bytes,11,opt,name=demand_level,json=demandLevel,proto3" json:"demand_level,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MajorInfo) Reset() {
	*x = MajorInfo{}
	mi := &file_app_score_rpc_score_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MajorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MajorInfo) ProtoMessage() {}

func (x *MajorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MajorInfo.ProtoReflect.Descriptor instead.
func (*MajorInfo) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{12}
}

func (x *MajorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MajorInfo) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *MajorInfo) GetMajorName() string {
	if x != nil {
		return x.MajorName
	}
	return ""
}

func (x *MajorInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MajorInfo) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

func (x *MajorInfo) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *MajorInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MajorInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MajorInfo) GetEmploymentDirection() string {
	if x != nil {
		return x.EmploymentDirection
	}
	return ""
}

func (x *MajorInfo) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *MajorInfo) GetDemandLevel() string {
	if x != nil {
		return x.DemandLevel
	}
	return ""
}

func (x *MajorInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetScoreTrendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollegeCode   string                 `protobuf:"bytes,1,opt,name=college_code,json=collegeCode,proto3" json:"college_code,omitempty"`
	MajorCode     string                 `protobuf:"bytes,2,opt,name=major_code,json=majorCode,proto3" json:"major_code,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType     int32                  `protobuf:"varint,4,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	Batch         string                 `protobuf:"bytes,5,opt,name=batch,proto3" json:"batch,omitempty"`
	Years         int32                  `protobuf:"varint,6,opt,name=years,proto3" json:"years,omitempty"` // 获取最近几年数据，默认5年
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreTrendReq) Reset() {
	*x = GetScoreTrendReq{}
	mi := &file_app_score_rpc_score_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreTrendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreTrendReq) ProtoMessage() {}

func (x *GetScoreTrendReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreTrendReq.ProtoReflect.Descriptor instead.
func (*GetScoreTrendReq) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{13}
}

func (x *GetScoreTrendReq) GetCollegeCode() string {
	if x != nil {
		return x.CollegeCode
	}
	return ""
}

func (x *GetScoreTrendReq) GetMajorCode() string {
	if x != nil {
		return x.MajorCode
	}
	return ""
}

func (x *GetScoreTrendReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetScoreTrendReq) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *GetScoreTrendReq) GetBatch() string {
	if x != nil {
		return x.Batch
	}
	return ""
}

func (x *GetScoreTrendReq) GetYears() int32 {
	if x != nil {
		return x.Years
	}
	return 0
}

type GetScoreTrendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trend         []*ScoreTrendPoint     `protobuf:"bytes,1,rep,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreTrendResp) Reset() {
	*x = GetScoreTrendResp{}
	mi := &file_app_score_rpc_score_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreTrendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreTrendResp) ProtoMessage() {}

func (x *GetScoreTrendResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreTrendResp.ProtoReflect.Descriptor instead.
func (*GetScoreTrendResp) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{14}
}

func (x *GetScoreTrendResp) GetTrend() []*ScoreTrendPoint {
	if x != nil {
		return x.Trend
	}
	return nil
}

type ScoreTrendPoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Year            int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	MinScore        int32                  `protobuf:"varint,2,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MinRank         int32                  `protobuf:"varint,3,opt,name=min_rank,json=minRank,proto3" json:"min_rank,omitempty"`
	AvgScore        int32                  `protobuf:"varint,4,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	EnrollmentCount int32                  `protobuf:"varint,5,opt,name=enrollment_count,json=enrollmentCount,proto3" json:"enrollment_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoreTrendPoint) Reset() {
	*x = ScoreTrendPoint{}
	mi := &file_app_score_rpc_score_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreTrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreTrendPoint) ProtoMessage() {}

func (x *ScoreTrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreTrendPoint.ProtoReflect.Descriptor instead.
func (*ScoreTrendPoint) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{15}
}

func (x *ScoreTrendPoint) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ScoreTrendPoint) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *ScoreTrendPoint) GetMinRank() int32 {
	if x != nil {
		return x.MinRank
	}
	return 0
}

func (x *ScoreTrendPoint) GetAvgScore() int32 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *ScoreTrendPoint) GetEnrollmentCount() int32 {
	if x != nil {
		return x.EnrollmentCount
	}
	return 0
}

type GetRankToScoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      string                 `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	ScoreType     int32                  `protobuf:"varint,2,opt,name=score_type,json=scoreType,proto3" json:"score_type,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankToScoreReq) Reset() {
	*x = GetRankToScoreReq{}
	mi := &file_app_score_rpc_score_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankToScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankToScoreReq) ProtoMessage() {}

func (x *GetRankToScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankToScoreReq.ProtoReflect.Descriptor instead.
func (*GetRankToScoreReq) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{16}
}

func (x *GetRankToScoreReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetRankToScoreReq) GetScoreType() int32 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *GetRankToScoreReq) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetRankToScoreReq) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GetRankToScoreResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EstimatedScore int32                  `protobuf:"varint,1,opt,name=estimated_score,json=estimatedScore,proto3" json:"estimated_score,omitempty"`
	Confidence     string                 `protobuf:"bytes,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // high, medium, low
	Note           string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRankToScoreResp) Reset() {
	*x = GetRankToScoreResp{}
	mi := &file_app_score_rpc_score_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankToScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankToScoreResp) ProtoMessage() {}

func (x *GetRankToScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_score_rpc_score_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankToScoreResp.ProtoReflect.Descriptor instead.
func (*GetRankToScoreResp) Descriptor() ([]byte, []int) {
	return file_app_score_rpc_score_proto_rawDescGZIP(), []int{17}
}

func (x *GetRankToScoreResp) GetEstimatedScore() int32 {
	if x != nil {
		return x.EstimatedScore
	}
	return 0
}

func (x *GetRankToScoreResp) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *GetRankToScoreResp) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_app_score_rpc_score_proto protoreflect.FileDescriptor

const file_app_score_rpc_score_proto_rawDesc = "" +
	"\n" +
	"\x19app/score/rpc/score.proto\x12\x05score\"\x99\x03\n" +
	"\x17QueryAdmissionScoresReq\x12\x1a\n" +
	"\bprovince\x18\x01 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x02 \x01(\x05R\tscoreType\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x05R\bminScore\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\x12\x19\n" +
	"\bmin_rank\x18\x05 \x01(\x05R\aminRank\x12\x19\n" +
	"\bmax_rank\x18\x06 \x01(\x05R\amaxRank\x12!\n" +
	"\fcollege_name\x18\a \x01(\tR\vcollegeName\x12\x1d\n" +
	"\n" +
	"major_name\x18\b \x01(\tR\tmajorName\x12\x14\n" +
	"\x05batch\x18\t \x01(\tR\x05batch\x12\x12\n" +
	"\x04year\x18\n" +
	" \x01(\x05R\x04year\x12\x12\n" +
	"\x04page\x18\v \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\f \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\r \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x0e \x01(\tR\tsortOrder\"\x90\x01\n" +
	"\x18QueryAdmissionScoresResp\x12-\n" +
	"\x06scores\x18\x01 \x03(\v2\x15.score.AdmissionScoreR\x06scores\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xec\x03\n" +
	"\x0eAdmissionScore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12!\n" +
	"\fcollege_code\x18\x04 \x01(\tR\vcollegeCode\x12!\n" +
	"\fcollege_name\x18\x05 \x01(\tR\vcollegeName\x12\x1d\n" +
	"\n" +
	"major_code\x18\x06 \x01(\tR\tmajorCode\x12\x1d\n" +
	"\n" +
	"major_name\x18\a \x01(\tR\tmajorName\x12\x14\n" +
	"\x05batch\x18\b \x01(\tR\x05batch\x12\x1d\n" +
	"\n" +
	"score_type\x18\t \x01(\x05R\tscoreType\x12\x1b\n" +
	"\tmin_score\x18\n" +
	" \x01(\x05R\bminScore\x12\x19\n" +
	"\bmin_rank\x18\v \x01(\x05R\aminRank\x12\x1b\n" +
	"\tavg_score\x18\f \x01(\x05R\bavgScore\x12)\n" +
	"\x10enrollment_count\x18\r \x01(\x05R\x0fenrollmentCount\x12\x1f\n" +
	"\vdata_source\x18\x0e \x01(\tR\n" +
	"dataSource\x12!\n" +
	"\fdata_quality\x18\x0f \x01(\x05R\vdataQuality\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\"6\n" +
	"\x11GetCollegeInfoReq\x12!\n" +
	"\fcollege_code\x18\x01 \x01(\tR\vcollegeCode\"B\n" +
	"\x12GetCollegeInfoResp\x12,\n" +
	"\acollege\x18\x01 \x01(\v2\x12.score.CollegeInfoR\acollege\"=\n" +
	"\x16BatchGetCollegeInfoReq\x12#\n" +
	"\rcollege_codes\x18\x01 \x03(\tR\fcollegeCodes\"I\n" +
	"\x17BatchGetCollegeInfoResp\x12.\n" +
	"\bcolleges\x18\x01 \x03(\v2\x12.score.CollegeInfoR\bcolleges\"\xf3\x02\n" +
	"\vCollegeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fcollege_code\x18\x02 \x01(\tR\vcollegeCode\x12!\n" +
	"\fcollege_name\x18\x03 \x01(\tR\vcollegeName\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x16\n" +
	"\x06nature\x18\b \x01(\tR\x06nature\x12\x18\n" +
	"\awebsite\x18\t \x01(\tR\awebsite\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x18\n" +
	"\aranking\x18\v \x01(\x05R\aranking\x12'\n" +
	"\x0femployment_rate\x18\f \x01(\x01R\x0eemploymentRate\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"0\n" +
	"\x0fGetMajorInfoReq\x12\x1d\n" +
	"\n" +
	"major_code\x18\x01 \x01(\tR\tmajorCode\":\n" +
	"\x10GetMajorInfoResp\x12&\n" +
	"\x05major\x18\x01 \x01(\v2\x10.score.MajorInfoR\x05major\"7\n" +
	"\x14BatchGetMajorInfoReq\x12\x1f\n" +
	"\vmajor_codes\x18\x01 \x03(\tR\n" +
	"majorCodes\"A\n" +
	"\x15BatchGetMajorInfoResp\x12(\n" +
	"\x06majors\x18\x01 \x03(\v2\x10.score.MajorInfoR\x06majors\"\x85\x03\n" +
	"\tMajorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"major_code\x18\x02 \x01(\tR\tmajorCode\x12\x1d\n" +
	"\n" +
	"major_name\x18\x03 \x01(\tR\tmajorName\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vsubcategory\x18\x05 \x01(\tR\vsubcategory\x12\x16\n" +
	"\x06degree\x18\x06 \x01(\tR\x06degree\x12\x1a\n" +
	"\bduration\x18\a \x01(\x05R\bduration\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x121\n" +
	"\x14employment_direction\x18\t \x01(\tR\x13employmentDirection\x12!\n" +
	"\fsalary_range\x18\n" +
	" \x01(\tR\vsalaryRange\x12!\n" +
	"\fdemand_level\x18\v \x01(\tR\vdemandLevel\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\xbb\x01\n" +
	"\x10GetScoreTrendReq\x12!\n" +
	"\fcollege_code\x18\x01 \x01(\tR\vcollegeCode\x12\x1d\n" +
	"\n" +
	"major_code\x18\x02 \x01(\tR\tmajorCode\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x04 \x01(\x05R\tscoreType\x12\x14\n" +
	"\x05batch\x18\x05 \x01(\tR\x05batch\x12\x14\n" +
	"\x05years\x18\x06 \x01(\x05R\x05years\"A\n" +
	"\x11GetScoreTrendResp\x12,\n" +
	"\x05trend\x18\x01 \x03(\v2\x16.score.ScoreTrendPointR\x05trend\"\xa5\x01\n" +
	"\x0fScoreTrendPoint\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1b\n" +
	"\tmin_score\x18\x02 \x01(\x05R\bminScore\x12\x19\n" +
	"\bmin_rank\x18\x03 \x01(\x05R\aminRank\x12\x1b\n" +
	"\tavg_score\x18\x04 \x01(\x05R\bavgScore\x12)\n" +
	"\x10enrollment_count\x18\x05 \x01(\x05R\x0fenrollmentCount\"v\n" +
	"\x11GetRankToScoreReq\x12\x1a\n" +
	"\bprovince\x18\x01 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"score_type\x18\x02 \x01(\x05R\tscoreType\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\"q\n" +
	"\x12GetRankToScoreResp\x12'\n" +
	"\x0festimated_score\x18\x01 \x01(\x05R\x0eestimatedScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\tR\n" +
	"confidence\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note2\x99\x04\n" +
	"\x05Score\x12W\n" +
	"\x14QueryAdmissionScores\x12\x1e.score.QueryAdmissionScoresReq\x1a\x1f.score.QueryAdmissionScoresResp\x12E\n" +
	"\x0eGetCollegeInfo\x12\x18.score.GetCollegeInfoReq\x1a\x19.score.GetCollegeInfoResp\x12T\n" +
	"\x13BatchGetCollegeInfo\x12\x1d.score.BatchGetCollegeInfoReq\x1a\x1e.score.BatchGetCollegeInfoResp\x12?\n" +
	"\fGetMajorInfo\x12\x16.score.GetMajorInfoReq\x1a\x17.score.GetMajorInfoResp\x12N\n" +
	"\x11BatchGetMajorInfo\x12\x1b.score.BatchGetMajorInfoReq\x1a\x1c.score.BatchGetMajorInfoResp\x12B\n" +
	"\rGetScoreTrend\x12\x17.score.GetScoreTrendReq\x1a\x18.score.GetScoreTrendResp\x12E\n" +
	"\x0eGetRankToScore\x12\x18.score.GetRankToScoreReq\x1a\x19.score.GetRankToScoreRespB*Z(lighthouse-volunteer/app/score/rpc/scoreb\x06proto3"

var (
	file_app_score_rpc_score_proto_rawDescOnce sync.Once
	file_app_score_rpc_score_proto_rawDescData []byte
)

func file_app_score_rpc_score_proto_rawDescGZIP() []byte {
	file_app_score_rpc_score_proto_rawDescOnce.Do(func() {
		file_app_score_rpc_score_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_score_rpc_score_proto_rawDesc), len(file_app_score_rpc_score_proto_rawDesc)))
	})
	return file_app_score_rpc_score_proto_rawDescData
}

var file_app_score_rpc_score_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_app_score_rpc_score_proto_goTypes = []any{
	(*QueryAdmissionScoresReq)(nil),  // 0: score.QueryAdmissionScoresReq
	(*QueryAdmissionScoresResp)(nil), // 1: score.QueryAdmissionScoresResp
	(*AdmissionScore)(nil),           // 2: score.AdmissionScore
	(*GetCollegeInfoReq)(nil),        // 3: score.GetCollegeInfoReq
	(*GetCollegeInfoResp)(nil),       // 4: score.GetCollegeInfoResp
	(*BatchGetCollegeInfoReq)(nil),   // 5: score.BatchGetCollegeInfoReq
	(*BatchGetCollegeInfoResp)(nil),  // 6: score.BatchGetCollegeInfoResp
	(*CollegeInfo)(nil),              // 7: score.CollegeInfo
	(*GetMajorInfoReq)(nil),          // 8: score.GetMajorInfoReq
	(*GetMajorInfoResp)(nil),         // 9: score.GetMajorInfoResp
	(*BatchGetMajorInfoReq)(nil),     // 10: score.BatchGetMajorInfoReq
	(*BatchGetMajorInfoResp)(nil),    // 11: score.BatchGetMajorInfoResp
	(*MajorInfo)(nil),                // 12: score.MajorInfo
	(*GetScoreTrendReq)(nil),         // 13: score.GetScoreTrendReq
	(*GetScoreTrendResp)(nil),        // 14: score.GetScoreTrendResp
	(*ScoreTrendPoint)(nil),          // 15: score.ScoreTrendPoint
	(*GetRankToScoreReq)(nil),        // 16: score.GetRankToScoreReq
	(*GetRankToScoreResp)(nil),       // 17: score.GetRankToScoreResp
}
var file_app_score_rpc_score_proto_depIdxs = []int32{
	2,  // 0: score.QueryAdmissionScoresResp.scores:type_name -> score.AdmissionScore
	7,  // 1: score.GetCollegeInfoResp.college:type_name -> score.CollegeInfo
	7,  // 2: score.BatchGetCollegeInfoResp.colleges:type_name -> score.CollegeInfo
	12, // 3: score.GetMajorInfoResp.major:type_name -> score.MajorInfo
	12, // 4: score.BatchGetMajorInfoResp.majors:type_name -> score.MajorInfo
	15, // 5: score.GetScoreTrendResp.trend:type_name -> score.ScoreTrendPoint
	0,  // 6: score.Score.QueryAdmissionScores:input_type -> score.QueryAdmissionScoresReq
	3,  // 7: score.Score.GetCollegeInfo:input_type -> score.GetCollegeInfoReq
	5,  // 8: score.Score.BatchGetCollegeInfo:input_type -> score.BatchGetCollegeInfoReq
	8,  // 9: score.Score.GetMajorInfo:input_type -> score.GetMajorInfoReq
	10, // 10: score.Score.BatchGetMajorInfo:input_type -> score.BatchGetMajorInfoReq
	13, // 11: score.Score.GetScoreTrend:input_type -> score.GetScoreTrendReq
	16, // 12: score.Score.GetRankToScore:input_type -> score.GetRankToScoreReq
	1,  // 13: score.Score.QueryAdmissionScores:output_type -> score.QueryAdmissionScoresResp
	4,  // 14: score.Score.GetCollegeInfo:output_type -> score.GetCollegeInfoResp
	6,  // 15: score.Score.BatchGetCollegeInfo:output_type -> score.BatchGetCollegeInfoResp
	9,  // 16: score.Score.GetMajorInfo:output_type -> score.GetMajorInfoResp
	11, // 17: score.Score.BatchGetMajorInfo:output_type -> score.BatchGetMajorInfoResp
	14, // 18: score.Score.GetScoreTrend:output_type -> score.GetScoreTrendResp
	17, // 19: score.Score.GetRankToScore:output_type -> score.GetRankToScoreResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_score_rpc_score_proto_init() }
func file_app_score_rpc_score_proto_init() {
	if File_app_score_rpc_score_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_score_rpc_score_proto_rawDesc), len(file_app_score_rpc_score_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_score_rpc_score_proto_goTypes,
		DependencyIndexes: file_app_score_rpc_score_proto_depIdxs,
		MessageInfos:      file_app_score_rpc_score_proto_msgTypes,
	}.Build()
	File_app_score_rpc_score_proto = out.File
	file_app_score_rpc_score_proto_goTypes = nil
	file_app_score_rpc_score_proto_depIdxs = nil
}
