// Code generated by goctl. DO NOT EDIT.

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// 请求和响应消息类型定义
type QueryScoreReq struct {
	Year      int32  `json:"year"`
	Province  string `json:"province"`
	College   string `json:"college"`
	Major     string `json:"major"`
	ScoreType int32  `json:"score_type"`
	Batch     string `json:"batch"`
	MinScore  int32  `json:"min_score"`
	MaxScore  int32  `json:"max_score"`
	Page      int32  `json:"page"`
	PageSize  int32  `json:"page_size"`
}

type QueryScoreResp struct {
	Code   int32             `json:"code"`
	Msg    string            `json:"msg"`
	Scores []*AdmissionScore `json:"scores"`
	Total  int64             `json:"total"`
}

type AdmissionScore struct {
	Id          int64  `json:"id"`
	Year        int32  `json:"year"`
	Province    string `json:"province"`
	CollegeName string `json:"college_name"`
	MajorName   string `json:"major_name"`
	ScoreType   int32  `json:"score_type"`
	Batch       string `json:"batch"`
	MinScore    int32  `json:"min_score"`
	MinRank     int32  `json:"min_rank"`
	DataSource  string `json:"data_source"`
	CreatedAt   string `json:"created_at"`
}

type QueryScoreTrendReq struct {
	College   string `json:"college"`
	Major     string `json:"major"`
	Province  string `json:"province"`
	StartYear int32  `json:"start_year"`
	EndYear   int32  `json:"end_year"`
}

type QueryScoreTrendResp struct {
	Code   int32         `json:"code"`
	Msg    string        `json:"msg"`
	Trends []*ScoreTrend `json:"trends"`
}

type ScoreTrend struct {
	Year     int32   `json:"year"`
	College  string  `json:"college"`
	Major    string  `json:"major"`
	MinScore int32   `json:"min_score"`
	MinRank  int32   `json:"min_rank"`
	AvgScore float64 `json:"avg_score"`
	Batch    string  `json:"batch"`
}

type GetMatchingCollegesReq struct {
	Score     int32  `json:"score"`
	Rank      int32  `json:"rank"`
	Province  string `json:"province"`
	Subjects  string `json:"subjects"`
	ScoreType int32  `json:"score_type"`
	Batch     string `json:"batch"`
	Limit     int32  `json:"limit"`
}

type GetMatchingCollegesResp struct {
	Code     int32              `json:"code"`
	Msg      string             `json:"msg"`
	Colleges []*MatchingCollege `json:"colleges"`
}

type MatchingCollege struct {
	CollegeName string  `json:"college_name"`
	MajorName   string  `json:"major_name"`
	MinScore    int32   `json:"min_score"`
	MinRank     int32   `json:"min_rank"`
	Batch       string  `json:"batch"`
	Year        int32   `json:"year"`
	Probability float64 `json:"probability"`
}

// DataClient is the client API for Data service.
type DataClient interface {
	QueryScore(ctx context.Context, in *QueryScoreReq, opts ...grpc.CallOption) (*QueryScoreResp, error)
	QueryScoreTrend(ctx context.Context, in *QueryScoreTrendReq, opts ...grpc.CallOption) (*QueryScoreTrendResp, error)
	GetMatchingColleges(ctx context.Context, in *GetMatchingCollegesReq, opts ...grpc.CallOption) (*GetMatchingCollegesResp, error)
}

type dataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataClient(cc grpc.ClientConnInterface) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) QueryScore(ctx context.Context, in *QueryScoreReq, opts ...grpc.CallOption) (*QueryScoreResp, error) {
	out := new(QueryScoreResp)
	err := c.cc.Invoke(ctx, "/data.Data/QueryScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) QueryScoreTrend(ctx context.Context, in *QueryScoreTrendReq, opts ...grpc.CallOption) (*QueryScoreTrendResp, error) {
	out := new(QueryScoreTrendResp)
	err := c.cc.Invoke(ctx, "/data.Data/QueryScoreTrend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) GetMatchingColleges(ctx context.Context, in *GetMatchingCollegesReq, opts ...grpc.CallOption) (*GetMatchingCollegesResp, error) {
	out := new(GetMatchingCollegesResp)
	err := c.cc.Invoke(ctx, "/data.Data/GetMatchingColleges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	QueryScore(context.Context, *QueryScoreReq) (*QueryScoreResp, error)
	QueryScoreTrend(context.Context, *QueryScoreTrendReq) (*QueryScoreTrendResp, error)
	GetMatchingColleges(context.Context, *GetMatchingCollegesReq) (*GetMatchingCollegesResp, error)
}

type UnimplementedDataServer struct{}

func (UnimplementedDataServer) QueryScore(context.Context, *QueryScoreReq) (*QueryScoreResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryScore not implemented")
}

func (UnimplementedDataServer) QueryScoreTrend(context.Context, *QueryScoreTrendReq) (*QueryScoreTrendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryScoreTrend not implemented")
}

func (UnimplementedDataServer) GetMatchingColleges(context.Context, *GetMatchingCollegesReq) (*GetMatchingCollegesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchingColleges not implemented")
}

func RegisterDataServer(s grpc.ServiceRegistrar, srv DataServer) {
	s.RegisterService(&Data_ServiceDesc, srv)
}

var Data_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryScore",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(QueryScoreReq)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil {
					return srv.(DataServer).QueryScore(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/data.Data/QueryScore",
				}
				handler := func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(DataServer).QueryScore(ctx, req.(*QueryScoreReq))
				}
				return interceptor(ctx, in, info, handler)
			},
		},
		{
			MethodName: "QueryScoreTrend",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(QueryScoreTrendReq)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil {
					return srv.(DataServer).QueryScoreTrend(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/data.Data/QueryScoreTrend",
				}
				handler := func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(DataServer).QueryScoreTrend(ctx, req.(*QueryScoreTrendReq))
				}
				return interceptor(ctx, in, info, handler)
			},
		},
		{
			MethodName: "GetMatchingColleges",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(GetMatchingCollegesReq)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil {
					return srv.(DataServer).GetMatchingColleges(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/data.Data/GetMatchingColleges",
				}
				handler := func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(DataServer).GetMatchingColleges(ctx, req.(*GetMatchingCollegesReq))
				}
				return interceptor(ctx, in, info, handler)
			},
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataClient interface {
	QueryScore(ctx context.Context, in *QueryScoreReq, opts ...grpc.CallOption) (*QueryScoreResp, error)
	QueryScoreTrend(ctx context.Context, in *QueryScoreTrendReq, opts ...grpc.CallOption) (*QueryScoreTrendResp, error)
	GetMatchingColleges(ctx context.Context, in *GetMatchingCollegesReq, opts ...grpc.CallOption) (*GetMatchingCollegesResp, error)
}

type dataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataClient(cc grpc.ClientConnInterface) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) QueryScore(ctx context.Context, in *QueryScoreReq, opts ...grpc.CallOption) (*QueryScoreResp, error) {
	c.MethodDescriptor
	out := new(QueryScoreResp)
	err := c.cc.Invoke(ctx, "/data.Data/QueryScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) QueryScoreTrend(ctx context.Context, in *QueryScoreTrendReq, opts ...grpc.CallOption) (*QueryScoreTrendResp, error) {
	out := new(QueryScoreTrendResp)
	err := c.cc.Invoke(ctx, "/data.Data/QueryScoreTrend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) GetMatchingColleges(ctx context.Context, in *GetMatchingCollegesReq, opts ...grpc.CallOption) (*GetMatchingCollegesResp, error) {
	out := new(GetMatchingCollegesResp)
	err := c.cc.Invoke(ctx, "/data.Data/GetMatchingColleges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	QueryScore(context.Context, *QueryScoreReq) (*QueryScoreResp, error)
	QueryScoreTrend(context.Context, *QueryScoreTrendReq) (*QueryScoreTrendResp, error)
	GetMatchingColleges(context.Context, *GetMatchingCollegesReq) (*GetMatchingCollegesResp, error)
	mustEmbedUnimplementedDataServer()
}

// UnimplementedDataServer must be embedded to have forward compatible implementations.
type UnimplementedDataServer struct {
}

func (UnimplementedDataServer) QueryScore(context.Context, *QueryScoreReq) (*QueryScoreResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryScore not implemented")
}

func (UnimplementedDataServer) QueryScoreTrend(context.Context, *QueryScoreTrendReq) (*QueryScoreTrendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryScoreTrend not implemented")
}

func (UnimplementedDataServer) GetMatchingColleges(context.Context, *GetMatchingCollegesReq) (*GetMatchingCollegesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchingColleges not implemented")
}

func (UnimplementedDataServer) mustEmbedUnimplementedDataServer() {}

func RegisterDataServer(s grpc.ServiceRegistrar, srv DataServer) {
	s.RegisterService(&Data_ServiceDesc, srv)
}

func _Data_QueryScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).QueryScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/QueryScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).QueryScore(ctx, req.(*QueryScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_QueryScoreTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryScoreTrendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).QueryScoreTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/QueryScoreTrend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).QueryScoreTrend(ctx, req.(*QueryScoreTrendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_GetMatchingColleges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchingCollegesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetMatchingColleges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/GetMatchingColleges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetMatchingColleges(ctx, req.(*GetMatchingCollegesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Data_ServiceDesc is the grpc.ServiceDesc for Data service.
// It is used to register the service with grpc.
var Data_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryScore",
			Handler:    _Data_QueryScore_Handler,
		},
		{
			MethodName: "QueryScoreTrend",
			Handler:    _Data_QueryScoreTrend_Handler,
		},
		{
			MethodName: "GetMatchingColleges",
			Handler:    _Data_GetMatchingColleges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
