// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package handler

import (
	"net/http"

	assessment "lighthouse-volunteer/app/api/internal/handler/assessment"
	college "lighthouse-volunteer/app/api/internal/handler/college"
	share "lighthouse-volunteer/app/api/internal/handler/share"
	user "lighthouse-volunteer/app/api/internal/handler/user"
	volunteer "lighthouse-volunteer/app/api/internal/handler/volunteer"
	"lighthouse-volunteer/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/assessment/career",
				Handler: assessment.CareerAssessmentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/assessment/subject-plan",
				Handler: assessment.SubjectPlanQueryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/college/list",
				Handler: college.CollegeQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/major/list",
				Handler: college.MajorQueryHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/share/:id/like",
				Handler: share.SeniorShareLikeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/share/create",
				Handler: share.SeniorShareCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/share/list",
				Handler: share.SeniorShareListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/profile",
				Handler: user.UserProfileUpdateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/volunteer/advice",
				Handler: volunteer.AIAdviceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/volunteer/scores",
				Handler: volunteer.ScoreQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/volunteer/suggestion",
				Handler: volunteer.VolunteerSuggestionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
