// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package handler

import (
	"net/http"

	"lighthouse-volunteer/gateway/lighthousegateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/ai/chat",
				Handler: AIChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/ai/recommendations",
				Handler: GetRecommendationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/career/result/:userId",
				Handler: GetCareerResultHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/career/test",
				Handler: CareerTestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/content",
				Handler: GetContentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/content/:id",
				Handler: GetContentDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/scores",
				Handler: QueryScoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/scores/trend",
				Handler: QueryScoreTrendHandler(serverCtx),
			},
		},
	)
}
