// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: spider.proto

package spiderClient

import (
	"context"

	"lighthouse-volunteer/pb/lighthouse-volunteer/app/spider/rpc/spider"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelSpiderTaskReq  = spider.CancelSpiderTaskReq
	CancelSpiderTaskResp = spider.CancelSpiderTaskResp
	CreateSpiderTaskReq  = spider.CreateSpiderTaskReq
	CreateSpiderTaskResp = spider.CreateSpiderTaskResp
	GetSpiderResultsReq  = spider.GetSpiderResultsReq
	GetSpiderResultsResp = spider.GetSpiderResultsResp
	GetSpiderTargetsReq  = spider.GetSpiderTargetsReq
	GetSpiderTargetsResp = spider.GetSpiderTargetsResp
	GetTaskStatusReq     = spider.GetTaskStatusReq
	GetTaskStatusResp    = spider.GetTaskStatusResp
	SpiderResult         = spider.SpiderResult
	SpiderTarget         = spider.SpiderTarget
	SpiderTask           = spider.SpiderTask

	Spider interface {
		// 获取爬虫目标列表
		GetSpiderTargets(ctx context.Context, in *GetSpiderTargetsReq, opts ...grpc.CallOption) (*GetSpiderTargetsResp, error)
		// 创建爬虫任务
		CreateSpiderTask(ctx context.Context, in *CreateSpiderTaskReq, opts ...grpc.CallOption) (*CreateSpiderTaskResp, error)
		// 获取任务状态
		GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusResp, error)
		// 取消爬虫任务
		CancelSpiderTask(ctx context.Context, in *CancelSpiderTaskReq, opts ...grpc.CallOption) (*CancelSpiderTaskResp, error)
		// 获取爬取结果
		GetSpiderResults(ctx context.Context, in *GetSpiderResultsReq, opts ...grpc.CallOption) (*GetSpiderResultsResp, error)
	}

	defaultSpider struct {
		cli zrpc.Client
	}
)

func NewSpider(cli zrpc.Client) Spider {
	return &defaultSpider{
		cli: cli,
	}
}

// 获取爬虫目标列表
func (m *defaultSpider) GetSpiderTargets(ctx context.Context, in *GetSpiderTargetsReq, opts ...grpc.CallOption) (*GetSpiderTargetsResp, error) {
	client := spider.NewSpiderClient(m.cli.Conn())
	return client.GetSpiderTargets(ctx, in, opts...)
}

// 创建爬虫任务
func (m *defaultSpider) CreateSpiderTask(ctx context.Context, in *CreateSpiderTaskReq, opts ...grpc.CallOption) (*CreateSpiderTaskResp, error) {
	client := spider.NewSpiderClient(m.cli.Conn())
	return client.CreateSpiderTask(ctx, in, opts...)
}

// 获取任务状态
func (m *defaultSpider) GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusResp, error) {
	client := spider.NewSpiderClient(m.cli.Conn())
	return client.GetTaskStatus(ctx, in, opts...)
}

// 取消爬虫任务
func (m *defaultSpider) CancelSpiderTask(ctx context.Context, in *CancelSpiderTaskReq, opts ...grpc.CallOption) (*CancelSpiderTaskResp, error) {
	client := spider.NewSpiderClient(m.cli.Conn())
	return client.CancelSpiderTask(ctx, in, opts...)
}

// 获取爬取结果
func (m *defaultSpider) GetSpiderResults(ctx context.Context, in *GetSpiderResultsReq, opts ...grpc.CallOption) (*GetSpiderResultsResp, error) {
	client := spider.NewSpiderClient(m.cli.Conn())
	return client.GetSpiderResults(ctx, in, opts...)
}
