// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package types

type AIAdviceReq struct {
	Query     string `json:"query"`
	UserID    int64  `json:"user_id"`
	SessionID string `json:"session_id"`
}

type AIAdviceResp struct {
	Answer    string   `json:"answer"`
	SessionID string   `json:"session_id"`
	Sources   []string `json:"sources"`
}

type BaseResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type CareerAssessmentReq struct {
	UserID         int64                  `json:"user_id"`
	AssessmentType string                 `json:"assessment_type"`
	Answers        map[string]interface{} `json:"answers"`
}

type CareerAssessmentResp struct {
	AssessmentType  string                 `json:"assessment_type"`
	Result          map[string]interface{} `json:"result"`
	ScoreDetails    map[string]interface{} `json:"score_details"`
	Recommendations string                 `json:"recommendations"`
	CreatedAt       string                 `json:"created_at"`
}

type CollegeInfo struct {
	CollegeCode    string  `json:"college_code"`
	CollegeName    string  `json:"college_name"`
	Province       string  `json:"province"`
	City           string  `json:"city"`
	Level          string  `json:"level"`
	Type           string  `json:"type"`
	Nature         string  `json:"nature"`
	Website        string  `json:"website"`
	Description    string  `json:"description"`
	Ranking        int     `json:"ranking"`
	EmploymentRate float64 `json:"employment_rate"`
}

type CollegeQueryReq struct {
	Page     int    `json:"page" form:"page"`
	PageSize int    `json:"page_size" form:"page_size"`
	Province string `json:"province" form:"province"`
	Level    string `json:"level" form:"level"`
	Type     string `json:"type" form:"type"`
	Name     string `json:"name" form:"name"`
}

type CollegeQueryResp struct {
	PageResponse
	List []CollegeInfo `json:"list"`
}

type CollegeSuggestion struct {
	CollegeCode string `json:"college_code"`
	CollegeName string `json:"college_name"`
	MajorCode   string `json:"major_code"`
	MajorName   string `json:"major_name"`
	Batch       string `json:"batch"`
	MinScore    int    `json:"min_score"`
	MinRank     int    `json:"min_rank"`
	Year        int    `json:"year"`
}

type MajorInfo struct {
	MajorCode           string `json:"major_code"`
	MajorName           string `json:"major_name"`
	Category            string `json:"category"`
	Subcategory         string `json:"subcategory"`
	Degree              string `json:"degree"`
	Duration            int    `json:"duration"`
	Description         string `json:"description"`
	EmploymentDirection string `json:"employment_direction"`
	SalaryRange         string `json:"salary_range"`
	DemandLevel         string `json:"demand_level"`
}

type MajorQueryReq struct {
	Page        int    `json:"page" form:"page"`
	PageSize    int    `json:"page_size" form:"page_size"`
	Category    string `json:"category" form:"category"`
	DemandLevel string `json:"demand_level" form:"demand_level"`
	Name        string `json:"name" form:"name"`
}

type MajorQueryResp struct {
	PageResponse
	List []MajorInfo `json:"list"`
}

type PageRequest struct {
	Page     int `json:"page" form:"page"`           // 页码，从1开始
	PageSize int `json:"page_size" form:"page_size"` // 每页大小
}

type PageResponse struct {
	Total    int64       `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"page_size"`
	Pages    int         `json:"pages"`
	List     interface{} `json:"list"`
}

type ScoreQueryReq struct {
	Province  string `json:"province" form:"province"`
	ScoreType int    `json:"score_type" form:"score_type"`
	Score     int    `json:"score" form:"score"`
	Rank      int    `json:"rank" form:"rank"`
	Subjects  string `json:"subjects" form:"subjects"`
}

type SeniorShareCreateReq struct {
	UserID      int64    `json:"user_id"`
	CollegeCode string   `json:"college_code"`
	CollegeName string   `json:"college_name"`
	MajorCode   string   `json:"major_code"`
	MajorName   string   `json:"major_name"`
	ShareType   string   `json:"share_type"`
	Title       string   `json:"title"`
	Content     string   `json:"content"`
	Tags        []string `json:"tags"`
	IsAnonymous int      `json:"is_anonymous"`
}

type SeniorShareInfo struct {
	ID           int64    `json:"id"`
	UserID       int64    `json:"user_id"`
	CollegeCode  string   `json:"college_code"`
	CollegeName  string   `json:"college_name"`
	MajorCode    string   `json:"major_code"`
	MajorName    string   `json:"major_name"`
	ShareType    string   `json:"share_type"`
	Title        string   `json:"title"`
	Content      string   `json:"content"`
	Tags         []string `json:"tags"`
	IsAnonymous  bool     `json:"is_anonymous"`
	ViewCount    int      `json:"view_count"`
	LikeCount    int      `json:"like_count"`
	CommentCount int      `json:"comment_count"`
	PublishedAt  string   `json:"published_at"`
	IsLiked      bool     `json:"is_liked"`
}

type SeniorShareLikeReq struct {
	UserID int64 `json:"user_id"`
}

type SeniorShareListReq struct {
	Page        int    `json:"page" form:"page"`
	PageSize    int    `json:"page_size" form:"page_size"`
	ShareType   string `json:"share_type" form:"share_type"`
	CollegeCode string `json:"college_code" form:"college_code"`
	MajorCode   string `json:"major_code" form:"major_code"`
	Keyword     string `json:"keyword" form:"keyword"`
	SortBy      string `json:"sort_by" form:"sort_by"`
}

type SeniorShareListResp struct {
	PageResponse
	List []SeniorShareInfo `json:"list"`
}

type SubjectPlanQueryReq struct {
	Province  string `json:"province" form:"province"`
	ScoreType int    `json:"score_type" form:"score_type"`
	Subjects  string `json:"subjects" form:"subjects"`
}

type SubjectPlanQueryResp struct {
	SubjectCombination string   `json:"subject_combination"`
	RecommendedMajors  []string `json:"recommended_majors"`
	SuccessRate        float64  `json:"success_rate"`
	AvgScoreRequired   int      `json:"avg_score_required"`
}

type UserLoginReq struct {
	Code string `json:"code" validate:"required"` // 微信授权码
}

type UserLoginResp struct {
	UserID      int64  `json:"user_id"`
	OpenID      string `json:"open_id"`
	Token       string `json:"token"`
	NeedProfile bool   `json:"need_profile"`
}

type UserProfileUpdateReq struct {
	UserID          int64    `json:"user_id"`
	GraduationYear  int      `json:"graduation_year"`
	Province        string   `json:"province"`
	ScoreType       int      `json:"score_type"`
	Subjects        string   `json:"subjects"`
	TotalScore      int      `json:"total_score"`
	Rank            int      `json:"rank"`
	TargetCollege   string   `json:"target_college"`
	TargetMajor     string   `json:"target_major"`
	InterestTags    []string `json:"interest_tags"`
	PersonalityType string   `json:"personality_type"`
}

type VolunteerSuggestionReq struct {
	Province     string   `json:"province"`
	ScoreType    int      `json:"score_type"`
	Score        int      `json:"score"`
	Rank         int      `json:"rank"`
	Subjects     string   `json:"subjects"`
	InterestTags []string `json:"interest_tags"`
}

type VolunteerSuggestionResp struct {
	Category string              `json:"category"`
	Colleges []CollegeSuggestion `json:"colleges"`
	Reason   string              `json:"reason"`
}
